/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AppAssistenteRouteImport } from './routes/app.assistente'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppCo2RouteImport } from './routes/app.co2'
import { Route as AppEscalaViagemRouteImport } from './routes/app.escala-viagem'
import { Route as AppEstrategicoRouteImport } from './routes/app.estrategico'
import { Route as AppEventosRouteImport } from './routes/app.eventos'
import { Route as AppGerencialRouteImport } from './routes/app.gerencial'
import { Route as AppMapaRouteImport } from './routes/app.mapa'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleAcessosRouteImport } from './routes/console.acessos'
import { Route as ConsoleAdministradoresRouteImport } from './routes/console.administradores'
import { Route as ConsoleAuditoriaRouteImport } from './routes/console.auditoria'
import { Route as ConsoleCatalogoRouteImport } from './routes/console.catalogo'
import { Route as ConsoleConfiguracoesRouteImport } from './routes/console.configuracoes'
import { Route as ConsoleContratosRouteImport } from './routes/console.contratos'
import { Route as ConsoleEstoqueRouteImport } from './routes/console.estoque'
import { Route as ConsoleIndicadoresRouteImport } from './routes/console.indicadores'
import { Route as ConsolePerfisRouteImport } from './routes/console.perfis'
import { Route as AppAdminCatalogoRouteImport } from './routes/app.admin.catalogo'
import { Route as AppAdminConfiguracoesRouteImport } from './routes/app.admin.configuracoes'
import { Route as AppAdminContratosRouteImport } from './routes/app.admin.contratos'
import { Route as AppCadastrosAlarmeRouteImport } from './routes/app.cadastros.alarme'
import { Route as AppCadastrosCercaRouteImport } from './routes/app.cadastros.cerca'
import { Route as AppCadastrosCombustivelRouteImport } from './routes/app.cadastros.combustivel'
import { Route as AppCadastrosDispositivosRouteImport } from './routes/app.cadastros.dispositivos'
import { Route as AppCadastrosEquipamentosRouteImport } from './routes/app.cadastros.equipamentos'
import { Route as AppCadastrosGaragensRouteImport } from './routes/app.cadastros.garagens'
import { Route as AppCadastrosGruposRouteImport } from './routes/app.cadastros.grupos'
import { Route as AppCadastrosGruposLinhasRouteImport } from './routes/app.cadastros.grupos-linhas'
import { Route as AppCadastrosLinhasRouteImport } from './routes/app.cadastros.linhas'
import { Route as AppCadastrosPontosRouteImport } from './routes/app.cadastros.pontos'
import { Route as AppCadastrosPontosInteresseRouteImport } from './routes/app.cadastros.pontos-interesse'
import { Route as AppCadastrosUnidadesRouteImport } from './routes/app.cadastros.unidades'
import { Route as AppCadastrosUsuariosRouteImport } from './routes/app.cadastros.usuarios'
import { Route as AppCadastrosVeiculosRouteImport } from './routes/app.cadastros.veiculos'
import { Route as AppFretamentoAssentosRouteImport } from './routes/app.fretamento.assentos'
import { Route as AppFretamentoCadastroPassageirosRouteImport } from './routes/app.fretamento.cadastro-passageiros'
import { Route as AppFretamentoCentrosCustoRouteImport } from './routes/app.fretamento.centros-custo'
import { Route as AppFretamentoEscalaRouteImport } from './routes/app.fretamento.escala'
import { Route as AppFretamentoPassageirosRouteImport } from './routes/app.fretamento.passageiros'
import { Route as AppFretamentoPontoRouteImport } from './routes/app.fretamento.ponto'
import { Route as AppFretamentoRotasRouteImport } from './routes/app.fretamento.rotas'
import { Route as AppFretamentoRoteirizacaoRouteImport } from './routes/app.fretamento.roteirizacao'
import { Route as AppFretamentoTurnosRouteImport } from './routes/app.fretamento.turnos'
import { Route as AppFrotaAnaliseRouteImport } from './routes/app.frota.analise'
import { Route as AppFrotaChecklistRouteImport } from './routes/app.frota.checklist'
import { Route as AppFrotaCombustivelRouteImport } from './routes/app.frota.combustivel'
import { Route as AppFrotaDesempenhoRouteImport } from './routes/app.frota.desempenho'
import { Route as AppFrotaDiagnosticoRouteImport } from './routes/app.frota.diagnostico'
import { Route as AppFrotaManutencaoRouteImport } from './routes/app.frota.manutencao'
import { Route as AppFrotaOrdensRouteImport } from './routes/app.frota.ordens'
import { Route as AppFrotaPneusRouteImport } from './routes/app.frota.pneus'
import { Route as AppFrotaRegeneracaoRouteImport } from './routes/app.frota.regeneracao'
import { Route as AppFrotaSinaisRouteImport } from './routes/app.frota.sinais'
import { Route as AppFrotaTelemetriaRouteImport } from './routes/app.frota.telemetria'
import { Route as AppFrotaTrackingRouteImport } from './routes/app.frota.tracking'
import { Route as AppGerencialIndicadoresRouteImport } from './routes/app.gerencial.indicadores'
import { Route as AppGerencialOperacionalRouteImport } from './routes/app.gerencial.operacional'
import { Route as AppManutencaoIndexRouteImport } from './routes/app.manutencao.index'
import { Route as AppManutencaoDiagnosticoRouteImport } from './routes/app.manutencao.diagnostico'
import { Route as AppManutencaoOrdensRouteImport } from './routes/app.manutencao.ordens'
import { Route as AppManutencaoPneusRouteImport } from './routes/app.manutencao.pneus'
import { Route as AppManutencaoRegeneracaoRouteImport } from './routes/app.manutencao.regeneracao'
import { Route as AppMotoristasIndexRouteImport } from './routes/app.motoristas.index'
import { Route as AppMotoristasNovoRouteImport } from './routes/app.motoristas.novo'
import { Route as AppOperacaoSinoticoRouteImport } from './routes/app.operacao.sinotico'
import { Route as AppOperacaoViagensRouteImport } from './routes/app.operacao.viagens'
import { Route as AppPessoasJornadaRouteImport } from './routes/app.pessoas.jornada'
import { Route as AppPessoasMultasRouteImport } from './routes/app.pessoas.multas'
import { Route as AppPremiacaoIndexRouteImport } from './routes/app.premiacao.index'
import { Route as AppPremiacaoMetasRouteImport } from './routes/app.premiacao.metas'
import { Route as AppRelatoriosOperacionaisRouteImport } from './routes/app.relatorios.operacionais'
import { Route as AppRelatoriosTelemetriaRouteImport } from './routes/app.relatorios.telemetria'
import { Route as AppSegurancaVideoRouteImport } from './routes/app.seguranca.video'
import { Route as AppUrbanoPadraoRouteImport } from './routes/app.urbano.padrao'
import { Route as AppUrbanoPassageirosRouteImport } from './routes/app.urbano.passageiros'
import { Route as AppVeiculosIndexRouteImport } from './routes/app.veiculos.index'
import { Route as AppVeiculosNovoRouteImport } from './routes/app.veiculos.novo'
import { Route as AppFretamentoViagensIndexRouteImport } from './routes/app.fretamento.viagens.index'
import { Route as AppFretamentoViagensNovaRouteImport } from './routes/app.fretamento.viagens.nova'
import { Route as AppMotoristasPerfilNomeRouteImport } from './routes/app.motoristas.perfil.$nome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppCo2Route = AppCo2RouteImport.update({
  id: '/co2',
  path: '/co2',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalaViagemRoute = AppEscalaViagemRouteImport.update({
  id: '/escala-viagem',
  path: '/escala-viagem',
  getParentRoute: () => AppRoute,
} as any)
const AppEstrategicoRoute = AppEstrategicoRouteImport.update({
  id: '/estrategico',
  path: '/estrategico',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppGerencialRoute = AppGerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAcessosRoute = ConsoleAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAdministradoresRoute = ConsoleAdministradoresRouteImport.update({
  id: '/administradores',
  path: '/administradores',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditoriaRoute = ConsoleAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleCatalogoRoute = ConsoleCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleConfiguracoesRoute = ConsoleConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleContratosRoute = ConsoleContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleEstoqueRoute = ConsoleEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleIndicadoresRoute = ConsoleIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePerfisRoute = ConsolePerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => ConsoleRoute,
} as any)
const AppAdminCatalogoRoute = AppAdminCatalogoRouteImport.update({
  id: '/admin/catalogo',
  path: '/admin/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminConfiguracoesRoute = AppAdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminContratosRoute = AppAdminContratosRouteImport.update({
  id: '/admin/contratos',
  path: '/admin/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosAlarmeRoute = AppCadastrosAlarmeRouteImport.update({
  id: '/cadastros/alarme',
  path: '/cadastros/alarme',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosCercaRoute = AppCadastrosCercaRouteImport.update({
  id: '/cadastros/cerca',
  path: '/cadastros/cerca',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosCombustivelRoute = AppCadastrosCombustivelRouteImport.update({
  id: '/cadastros/combustivel',
  path: '/cadastros/combustivel',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosDispositivosRoute =
  AppCadastrosDispositivosRouteImport.update({
    id: '/cadastros/dispositivos',
    path: '/cadastros/dispositivos',
    getParentRoute: () => AppRoute,
  } as any)
const AppCadastrosEquipamentosRoute =
  AppCadastrosEquipamentosRouteImport.update({
    id: '/cadastros/equipamentos',
    path: '/cadastros/equipamentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppCadastrosGaragensRoute = AppCadastrosGaragensRouteImport.update({
  id: '/cadastros/garagens',
  path: '/cadastros/garagens',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosGruposRoute = AppCadastrosGruposRouteImport.update({
  id: '/cadastros/grupos',
  path: '/cadastros/grupos',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosGruposLinhasRoute =
  AppCadastrosGruposLinhasRouteImport.update({
    id: '/cadastros/grupos-linhas',
    path: '/cadastros/grupos-linhas',
    getParentRoute: () => AppRoute,
  } as any)
const AppCadastrosLinhasRoute = AppCadastrosLinhasRouteImport.update({
  id: '/cadastros/linhas',
  path: '/cadastros/linhas',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosPontosRoute = AppCadastrosPontosRouteImport.update({
  id: '/cadastros/pontos',
  path: '/cadastros/pontos',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosPontosInteresseRoute =
  AppCadastrosPontosInteresseRouteImport.update({
    id: '/cadastros/pontos-interesse',
    path: '/cadastros/pontos-interesse',
    getParentRoute: () => AppRoute,
  } as any)
const AppCadastrosUnidadesRoute = AppCadastrosUnidadesRouteImport.update({
  id: '/cadastros/unidades',
  path: '/cadastros/unidades',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosUsuariosRoute = AppCadastrosUsuariosRouteImport.update({
  id: '/cadastros/usuarios',
  path: '/cadastros/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosVeiculosRoute = AppCadastrosVeiculosRouteImport.update({
  id: '/cadastros/veiculos',
  path: '/cadastros/veiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoAssentosRoute = AppFretamentoAssentosRouteImport.update({
  id: '/fretamento/assentos',
  path: '/fretamento/assentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoCadastroPassageirosRoute =
  AppFretamentoCadastroPassageirosRouteImport.update({
    id: '/fretamento/cadastro-passageiros',
    path: '/fretamento/cadastro-passageiros',
    getParentRoute: () => AppRoute,
  } as any)
const AppFretamentoCentrosCustoRoute =
  AppFretamentoCentrosCustoRouteImport.update({
    id: '/fretamento/centros-custo',
    path: '/fretamento/centros-custo',
    getParentRoute: () => AppRoute,
  } as any)
const AppFretamentoEscalaRoute = AppFretamentoEscalaRouteImport.update({
  id: '/fretamento/escala',
  path: '/fretamento/escala',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoPassageirosRoute =
  AppFretamentoPassageirosRouteImport.update({
    id: '/fretamento/passageiros',
    path: '/fretamento/passageiros',
    getParentRoute: () => AppRoute,
  } as any)
const AppFretamentoPontoRoute = AppFretamentoPontoRouteImport.update({
  id: '/fretamento/ponto',
  path: '/fretamento/ponto',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoRotasRoute = AppFretamentoRotasRouteImport.update({
  id: '/fretamento/rotas',
  path: '/fretamento/rotas',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoRoteirizacaoRoute =
  AppFretamentoRoteirizacaoRouteImport.update({
    id: '/fretamento/roteirizacao',
    path: '/fretamento/roteirizacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppFretamentoTurnosRoute = AppFretamentoTurnosRouteImport.update({
  id: '/fretamento/turnos',
  path: '/fretamento/turnos',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaAnaliseRoute = AppFrotaAnaliseRouteImport.update({
  id: '/frota/analise',
  path: '/frota/analise',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaChecklistRoute = AppFrotaChecklistRouteImport.update({
  id: '/frota/checklist',
  path: '/frota/checklist',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaCombustivelRoute = AppFrotaCombustivelRouteImport.update({
  id: '/frota/combustivel',
  path: '/frota/combustivel',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaDesempenhoRoute = AppFrotaDesempenhoRouteImport.update({
  id: '/frota/desempenho',
  path: '/frota/desempenho',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaDiagnosticoRoute = AppFrotaDiagnosticoRouteImport.update({
  id: '/frota/diagnostico',
  path: '/frota/diagnostico',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaManutencaoRoute = AppFrotaManutencaoRouteImport.update({
  id: '/frota/manutencao',
  path: '/frota/manutencao',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaOrdensRoute = AppFrotaOrdensRouteImport.update({
  id: '/frota/ordens',
  path: '/frota/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaPneusRoute = AppFrotaPneusRouteImport.update({
  id: '/frota/pneus',
  path: '/frota/pneus',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaRegeneracaoRoute = AppFrotaRegeneracaoRouteImport.update({
  id: '/frota/regeneracao',
  path: '/frota/regeneracao',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaSinaisRoute = AppFrotaSinaisRouteImport.update({
  id: '/frota/sinais',
  path: '/frota/sinais',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaTelemetriaRoute = AppFrotaTelemetriaRouteImport.update({
  id: '/frota/telemetria',
  path: '/frota/telemetria',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaTrackingRoute = AppFrotaTrackingRouteImport.update({
  id: '/frota/tracking',
  path: '/frota/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppGerencialIndicadoresRoute = AppGerencialIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => AppGerencialRoute,
} as any)
const AppGerencialOperacionalRoute = AppGerencialOperacionalRouteImport.update({
  id: '/operacional',
  path: '/operacional',
  getParentRoute: () => AppGerencialRoute,
} as any)
const AppManutencaoIndexRoute = AppManutencaoIndexRouteImport.update({
  id: '/manutencao/',
  path: '/manutencao/',
  getParentRoute: () => AppRoute,
} as any)
const AppManutencaoDiagnosticoRoute =
  AppManutencaoDiagnosticoRouteImport.update({
    id: '/manutencao/diagnostico',
    path: '/manutencao/diagnostico',
    getParentRoute: () => AppRoute,
  } as any)
const AppManutencaoOrdensRoute = AppManutencaoOrdensRouteImport.update({
  id: '/manutencao/ordens',
  path: '/manutencao/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppManutencaoPneusRoute = AppManutencaoPneusRouteImport.update({
  id: '/manutencao/pneus',
  path: '/manutencao/pneus',
  getParentRoute: () => AppRoute,
} as any)
const AppManutencaoRegeneracaoRoute =
  AppManutencaoRegeneracaoRouteImport.update({
    id: '/manutencao/regeneracao',
    path: '/manutencao/regeneracao',
    getParentRoute: () => AppRoute,
  } as any)
const AppMotoristasIndexRoute = AppMotoristasIndexRouteImport.update({
  id: '/motoristas/',
  path: '/motoristas/',
  getParentRoute: () => AppRoute,
} as any)
const AppMotoristasNovoRoute = AppMotoristasNovoRouteImport.update({
  id: '/motoristas/novo',
  path: '/motoristas/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacaoSinoticoRoute = AppOperacaoSinoticoRouteImport.update({
  id: '/operacao/sinotico',
  path: '/operacao/sinotico',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacaoViagensRoute = AppOperacaoViagensRouteImport.update({
  id: '/operacao/viagens',
  path: '/operacao/viagens',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasJornadaRoute = AppPessoasJornadaRouteImport.update({
  id: '/pessoas/jornada',
  path: '/pessoas/jornada',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasMultasRoute = AppPessoasMultasRouteImport.update({
  id: '/pessoas/multas',
  path: '/pessoas/multas',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiacaoIndexRoute = AppPremiacaoIndexRouteImport.update({
  id: '/premiacao/',
  path: '/premiacao/',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiacaoMetasRoute = AppPremiacaoMetasRouteImport.update({
  id: '/premiacao/metas',
  path: '/premiacao/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosOperacionaisRoute =
  AppRelatoriosOperacionaisRouteImport.update({
    id: '/operacionais',
    path: '/operacionais',
    getParentRoute: () => AppRelatoriosRoute,
  } as any)
const AppRelatoriosTelemetriaRoute = AppRelatoriosTelemetriaRouteImport.update({
  id: '/telemetria',
  path: '/telemetria',
  getParentRoute: () => AppRelatoriosRoute,
} as any)
const AppSegurancaVideoRoute = AppSegurancaVideoRouteImport.update({
  id: '/seguranca/video',
  path: '/seguranca/video',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanoPadraoRoute = AppUrbanoPadraoRouteImport.update({
  id: '/urbano/padrao',
  path: '/urbano/padrao',
  getParentRoute: () => AppRoute,
} as any)
const AppUrbanoPassageirosRoute = AppUrbanoPassageirosRouteImport.update({
  id: '/urbano/passageiros',
  path: '/urbano/passageiros',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosIndexRoute = AppVeiculosIndexRouteImport.update({
  id: '/veiculos/',
  path: '/veiculos/',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosNovoRoute = AppVeiculosNovoRouteImport.update({
  id: '/veiculos/novo',
  path: '/veiculos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoViagensIndexRoute =
  AppFretamentoViagensIndexRouteImport.update({
    id: '/fretamento/viagens/',
    path: '/fretamento/viagens/',
    getParentRoute: () => AppRoute,
  } as any)
const AppFretamentoViagensNovaRoute =
  AppFretamentoViagensNovaRouteImport.update({
    id: '/fretamento/viagens/nova',
    path: '/fretamento/viagens/nova',
    getParentRoute: () => AppRoute,
  } as any)
const AppMotoristasPerfilNomeRoute = AppMotoristasPerfilNomeRouteImport.update({
  id: '/motoristas/perfil/$nome',
  path: '/motoristas/perfil/$nome',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/co2': typeof AppCo2Route
  '/app/escala-viagem': typeof AppEscalaViagemRoute
  '/app/estrategico': typeof AppEstrategicoRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/gerencial': typeof AppGerencialRouteWithChildren
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRouteWithChildren
  '/app/suporte': typeof AppSuporteRoute
  '/console/acessos': typeof ConsoleAcessosRoute
  '/console/administradores': typeof ConsoleAdministradoresRoute
  '/console/auditoria': typeof ConsoleAuditoriaRoute
  '/console/catalogo': typeof ConsoleCatalogoRoute
  '/console/configuracoes': typeof ConsoleConfiguracoesRoute
  '/console/contratos': typeof ConsoleContratosRoute
  '/console/estoque': typeof ConsoleEstoqueRoute
  '/console/indicadores': typeof ConsoleIndicadoresRoute
  '/console/perfis': typeof ConsolePerfisRoute
  '/app/': typeof AppIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/app/admin/catalogo': typeof AppAdminCatalogoRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/contratos': typeof AppAdminContratosRoute
  '/app/cadastros/alarme': typeof AppCadastrosAlarmeRoute
  '/app/cadastros/cerca': typeof AppCadastrosCercaRoute
  '/app/cadastros/combustivel': typeof AppCadastrosCombustivelRoute
  '/app/cadastros/dispositivos': typeof AppCadastrosDispositivosRoute
  '/app/cadastros/equipamentos': typeof AppCadastrosEquipamentosRoute
  '/app/cadastros/garagens': typeof AppCadastrosGaragensRoute
  '/app/cadastros/grupos': typeof AppCadastrosGruposRoute
  '/app/cadastros/grupos-linhas': typeof AppCadastrosGruposLinhasRoute
  '/app/cadastros/linhas': typeof AppCadastrosLinhasRoute
  '/app/cadastros/pontos': typeof AppCadastrosPontosRoute
  '/app/cadastros/pontos-interesse': typeof AppCadastrosPontosInteresseRoute
  '/app/cadastros/unidades': typeof AppCadastrosUnidadesRoute
  '/app/cadastros/usuarios': typeof AppCadastrosUsuariosRoute
  '/app/cadastros/veiculos': typeof AppCadastrosVeiculosRoute
  '/app/fretamento/assentos': typeof AppFretamentoAssentosRoute
  '/app/fretamento/cadastro-passageiros': typeof AppFretamentoCadastroPassageirosRoute
  '/app/fretamento/centros-custo': typeof AppFretamentoCentrosCustoRoute
  '/app/fretamento/escala': typeof AppFretamentoEscalaRoute
  '/app/fretamento/passageiros': typeof AppFretamentoPassageirosRoute
  '/app/fretamento/ponto': typeof AppFretamentoPontoRoute
  '/app/fretamento/rotas': typeof AppFretamentoRotasRoute
  '/app/fretamento/roteirizacao': typeof AppFretamentoRoteirizacaoRoute
  '/app/fretamento/turnos': typeof AppFretamentoTurnosRoute
  '/app/frota/analise': typeof AppFrotaAnaliseRoute
  '/app/frota/checklist': typeof AppFrotaChecklistRoute
  '/app/frota/combustivel': typeof AppFrotaCombustivelRoute
  '/app/frota/desempenho': typeof AppFrotaDesempenhoRoute
  '/app/frota/diagnostico': typeof AppFrotaDiagnosticoRoute
  '/app/frota/manutencao': typeof AppFrotaManutencaoRoute
  '/app/frota/ordens': typeof AppFrotaOrdensRoute
  '/app/frota/pneus': typeof AppFrotaPneusRoute
  '/app/frota/regeneracao': typeof AppFrotaRegeneracaoRoute
  '/app/frota/sinais': typeof AppFrotaSinaisRoute
  '/app/frota/telemetria': typeof AppFrotaTelemetriaRoute
  '/app/frota/tracking': typeof AppFrotaTrackingRoute
  '/app/gerencial/indicadores': typeof AppGerencialIndicadoresRoute
  '/app/gerencial/operacional': typeof AppGerencialOperacionalRoute
  '/app/manutencao/diagnostico': typeof AppManutencaoDiagnosticoRoute
  '/app/manutencao/ordens': typeof AppManutencaoOrdensRoute
  '/app/manutencao/pneus': typeof AppManutencaoPneusRoute
  '/app/manutencao/regeneracao': typeof AppManutencaoRegeneracaoRoute
  '/app/motoristas/novo': typeof AppMotoristasNovoRoute
  '/app/operacao/sinotico': typeof AppOperacaoSinoticoRoute
  '/app/operacao/viagens': typeof AppOperacaoViagensRoute
  '/app/pessoas/jornada': typeof AppPessoasJornadaRoute
  '/app/pessoas/multas': typeof AppPessoasMultasRoute
  '/app/premiacao/metas': typeof AppPremiacaoMetasRoute
  '/app/relatorios/operacionais': typeof AppRelatoriosOperacionaisRoute
  '/app/relatorios/telemetria': typeof AppRelatoriosTelemetriaRoute
  '/app/seguranca/video': typeof AppSegurancaVideoRoute
  '/app/urbano/padrao': typeof AppUrbanoPadraoRoute
  '/app/urbano/passageiros': typeof AppUrbanoPassageirosRoute
  '/app/veiculos/novo': typeof AppVeiculosNovoRoute
  '/app/manutencao/': typeof AppManutencaoIndexRoute
  '/app/motoristas/': typeof AppMotoristasIndexRoute
  '/app/premiacao/': typeof AppPremiacaoIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
  '/app/fretamento/viagens/nova': typeof AppFretamentoViagensNovaRoute
  '/app/motoristas/perfil/$nome': typeof AppMotoristasPerfilNomeRoute
  '/app/fretamento/viagens/': typeof AppFretamentoViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/co2': typeof AppCo2Route
  '/app/escala-viagem': typeof AppEscalaViagemRoute
  '/app/estrategico': typeof AppEstrategicoRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/gerencial': typeof AppGerencialRouteWithChildren
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRouteWithChildren
  '/app/suporte': typeof AppSuporteRoute
  '/console/acessos': typeof ConsoleAcessosRoute
  '/console/administradores': typeof ConsoleAdministradoresRoute
  '/console/auditoria': typeof ConsoleAuditoriaRoute
  '/console/catalogo': typeof ConsoleCatalogoRoute
  '/console/configuracoes': typeof ConsoleConfiguracoesRoute
  '/console/contratos': typeof ConsoleContratosRoute
  '/console/estoque': typeof ConsoleEstoqueRoute
  '/console/indicadores': typeof ConsoleIndicadoresRoute
  '/console/perfis': typeof ConsolePerfisRoute
  '/app': typeof AppIndexRoute
  '/console': typeof ConsoleIndexRoute
  '/app/admin/catalogo': typeof AppAdminCatalogoRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/contratos': typeof AppAdminContratosRoute
  '/app/cadastros/alarme': typeof AppCadastrosAlarmeRoute
  '/app/cadastros/cerca': typeof AppCadastrosCercaRoute
  '/app/cadastros/combustivel': typeof AppCadastrosCombustivelRoute
  '/app/cadastros/dispositivos': typeof AppCadastrosDispositivosRoute
  '/app/cadastros/equipamentos': typeof AppCadastrosEquipamentosRoute
  '/app/cadastros/garagens': typeof AppCadastrosGaragensRoute
  '/app/cadastros/grupos': typeof AppCadastrosGruposRoute
  '/app/cadastros/grupos-linhas': typeof AppCadastrosGruposLinhasRoute
  '/app/cadastros/linhas': typeof AppCadastrosLinhasRoute
  '/app/cadastros/pontos': typeof AppCadastrosPontosRoute
  '/app/cadastros/pontos-interesse': typeof AppCadastrosPontosInteresseRoute
  '/app/cadastros/unidades': typeof AppCadastrosUnidadesRoute
  '/app/cadastros/usuarios': typeof AppCadastrosUsuariosRoute
  '/app/cadastros/veiculos': typeof AppCadastrosVeiculosRoute
  '/app/fretamento/assentos': typeof AppFretamentoAssentosRoute
  '/app/fretamento/cadastro-passageiros': typeof AppFretamentoCadastroPassageirosRoute
  '/app/fretamento/centros-custo': typeof AppFretamentoCentrosCustoRoute
  '/app/fretamento/escala': typeof AppFretamentoEscalaRoute
  '/app/fretamento/passageiros': typeof AppFretamentoPassageirosRoute
  '/app/fretamento/ponto': typeof AppFretamentoPontoRoute
  '/app/fretamento/rotas': typeof AppFretamentoRotasRoute
  '/app/fretamento/roteirizacao': typeof AppFretamentoRoteirizacaoRoute
  '/app/fretamento/turnos': typeof AppFretamentoTurnosRoute
  '/app/frota/analise': typeof AppFrotaAnaliseRoute
  '/app/frota/checklist': typeof AppFrotaChecklistRoute
  '/app/frota/combustivel': typeof AppFrotaCombustivelRoute
  '/app/frota/desempenho': typeof AppFrotaDesempenhoRoute
  '/app/frota/diagnostico': typeof AppFrotaDiagnosticoRoute
  '/app/frota/manutencao': typeof AppFrotaManutencaoRoute
  '/app/frota/ordens': typeof AppFrotaOrdensRoute
  '/app/frota/pneus': typeof AppFrotaPneusRoute
  '/app/frota/regeneracao': typeof AppFrotaRegeneracaoRoute
  '/app/frota/sinais': typeof AppFrotaSinaisRoute
  '/app/frota/telemetria': typeof AppFrotaTelemetriaRoute
  '/app/frota/tracking': typeof AppFrotaTrackingRoute
  '/app/gerencial/indicadores': typeof AppGerencialIndicadoresRoute
  '/app/gerencial/operacional': typeof AppGerencialOperacionalRoute
  '/app/manutencao/diagnostico': typeof AppManutencaoDiagnosticoRoute
  '/app/manutencao/ordens': typeof AppManutencaoOrdensRoute
  '/app/manutencao/pneus': typeof AppManutencaoPneusRoute
  '/app/manutencao/regeneracao': typeof AppManutencaoRegeneracaoRoute
  '/app/motoristas/novo': typeof AppMotoristasNovoRoute
  '/app/operacao/sinotico': typeof AppOperacaoSinoticoRoute
  '/app/operacao/viagens': typeof AppOperacaoViagensRoute
  '/app/pessoas/jornada': typeof AppPessoasJornadaRoute
  '/app/pessoas/multas': typeof AppPessoasMultasRoute
  '/app/premiacao/metas': typeof AppPremiacaoMetasRoute
  '/app/relatorios/operacionais': typeof AppRelatoriosOperacionaisRoute
  '/app/relatorios/telemetria': typeof AppRelatoriosTelemetriaRoute
  '/app/seguranca/video': typeof AppSegurancaVideoRoute
  '/app/urbano/padrao': typeof AppUrbanoPadraoRoute
  '/app/urbano/passageiros': typeof AppUrbanoPassageirosRoute
  '/app/veiculos/novo': typeof AppVeiculosNovoRoute
  '/app/manutencao': typeof AppManutencaoIndexRoute
  '/app/motoristas': typeof AppMotoristasIndexRoute
  '/app/premiacao': typeof AppPremiacaoIndexRoute
  '/app/veiculos': typeof AppVeiculosIndexRoute
  '/app/fretamento/viagens/nova': typeof AppFretamentoViagensNovaRoute
  '/app/motoristas/perfil/$nome': typeof AppMotoristasPerfilNomeRoute
  '/app/fretamento/viagens': typeof AppFretamentoViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/co2': typeof AppCo2Route
  '/app/escala-viagem': typeof AppEscalaViagemRoute
  '/app/estrategico': typeof AppEstrategicoRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/gerencial': typeof AppGerencialRouteWithChildren
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRouteWithChildren
  '/app/suporte': typeof AppSuporteRoute
  '/console/acessos': typeof ConsoleAcessosRoute
  '/console/administradores': typeof ConsoleAdministradoresRoute
  '/console/auditoria': typeof ConsoleAuditoriaRoute
  '/console/catalogo': typeof ConsoleCatalogoRoute
  '/console/configuracoes': typeof ConsoleConfiguracoesRoute
  '/console/contratos': typeof ConsoleContratosRoute
  '/console/estoque': typeof ConsoleEstoqueRoute
  '/console/indicadores': typeof ConsoleIndicadoresRoute
  '/console/perfis': typeof ConsolePerfisRoute
  '/app/': typeof AppIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/app/admin/catalogo': typeof AppAdminCatalogoRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/contratos': typeof AppAdminContratosRoute
  '/app/cadastros/alarme': typeof AppCadastrosAlarmeRoute
  '/app/cadastros/cerca': typeof AppCadastrosCercaRoute
  '/app/cadastros/combustivel': typeof AppCadastrosCombustivelRoute
  '/app/cadastros/dispositivos': typeof AppCadastrosDispositivosRoute
  '/app/cadastros/equipamentos': typeof AppCadastrosEquipamentosRoute
  '/app/cadastros/garagens': typeof AppCadastrosGaragensRoute
  '/app/cadastros/grupos': typeof AppCadastrosGruposRoute
  '/app/cadastros/grupos-linhas': typeof AppCadastrosGruposLinhasRoute
  '/app/cadastros/linhas': typeof AppCadastrosLinhasRoute
  '/app/cadastros/pontos': typeof AppCadastrosPontosRoute
  '/app/cadastros/pontos-interesse': typeof AppCadastrosPontosInteresseRoute
  '/app/cadastros/unidades': typeof AppCadastrosUnidadesRoute
  '/app/cadastros/usuarios': typeof AppCadastrosUsuariosRoute
  '/app/cadastros/veiculos': typeof AppCadastrosVeiculosRoute
  '/app/fretamento/assentos': typeof AppFretamentoAssentosRoute
  '/app/fretamento/cadastro-passageiros': typeof AppFretamentoCadastroPassageirosRoute
  '/app/fretamento/centros-custo': typeof AppFretamentoCentrosCustoRoute
  '/app/fretamento/escala': typeof AppFretamentoEscalaRoute
  '/app/fretamento/passageiros': typeof AppFretamentoPassageirosRoute
  '/app/fretamento/ponto': typeof AppFretamentoPontoRoute
  '/app/fretamento/rotas': typeof AppFretamentoRotasRoute
  '/app/fretamento/roteirizacao': typeof AppFretamentoRoteirizacaoRoute
  '/app/fretamento/turnos': typeof AppFretamentoTurnosRoute
  '/app/frota/analise': typeof AppFrotaAnaliseRoute
  '/app/frota/checklist': typeof AppFrotaChecklistRoute
  '/app/frota/combustivel': typeof AppFrotaCombustivelRoute
  '/app/frota/desempenho': typeof AppFrotaDesempenhoRoute
  '/app/frota/diagnostico': typeof AppFrotaDiagnosticoRoute
  '/app/frota/manutencao': typeof AppFrotaManutencaoRoute
  '/app/frota/ordens': typeof AppFrotaOrdensRoute
  '/app/frota/pneus': typeof AppFrotaPneusRoute
  '/app/frota/regeneracao': typeof AppFrotaRegeneracaoRoute
  '/app/frota/sinais': typeof AppFrotaSinaisRoute
  '/app/frota/telemetria': typeof AppFrotaTelemetriaRoute
  '/app/frota/tracking': typeof AppFrotaTrackingRoute
  '/app/gerencial/indicadores': typeof AppGerencialIndicadoresRoute
  '/app/gerencial/operacional': typeof AppGerencialOperacionalRoute
  '/app/manutencao/diagnostico': typeof AppManutencaoDiagnosticoRoute
  '/app/manutencao/ordens': typeof AppManutencaoOrdensRoute
  '/app/manutencao/pneus': typeof AppManutencaoPneusRoute
  '/app/manutencao/regeneracao': typeof AppManutencaoRegeneracaoRoute
  '/app/motoristas/novo': typeof AppMotoristasNovoRoute
  '/app/operacao/sinotico': typeof AppOperacaoSinoticoRoute
  '/app/operacao/viagens': typeof AppOperacaoViagensRoute
  '/app/pessoas/jornada': typeof AppPessoasJornadaRoute
  '/app/pessoas/multas': typeof AppPessoasMultasRoute
  '/app/premiacao/metas': typeof AppPremiacaoMetasRoute
  '/app/relatorios/operacionais': typeof AppRelatoriosOperacionaisRoute
  '/app/relatorios/telemetria': typeof AppRelatoriosTelemetriaRoute
  '/app/seguranca/video': typeof AppSegurancaVideoRoute
  '/app/urbano/padrao': typeof AppUrbanoPadraoRoute
  '/app/urbano/passageiros': typeof AppUrbanoPassageirosRoute
  '/app/veiculos/novo': typeof AppVeiculosNovoRoute
  '/app/manutencao/': typeof AppManutencaoIndexRoute
  '/app/motoristas/': typeof AppMotoristasIndexRoute
  '/app/premiacao/': typeof AppPremiacaoIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
  '/app/fretamento/viagens/nova': typeof AppFretamentoViagensNovaRoute
  '/app/motoristas/perfil/$nome': typeof AppMotoristasPerfilNomeRoute
  '/app/fretamento/viagens/': typeof AppFretamentoViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/console'
    | '/embed'
    | '/login'
    | '/app/$'
    | '/app/assistente'
    | '/app/auditoria'
    | '/app/co2'
    | '/app/escala-viagem'
    | '/app/estrategico'
    | '/app/eventos'
    | '/app/gerencial'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app/suporte'
    | '/console/acessos'
    | '/console/administradores'
    | '/console/auditoria'
    | '/console/catalogo'
    | '/console/configuracoes'
    | '/console/contratos'
    | '/console/estoque'
    | '/console/indicadores'
    | '/console/perfis'
    | '/app/'
    | '/console/'
    | '/app/admin/catalogo'
    | '/app/admin/configuracoes'
    | '/app/admin/contratos'
    | '/app/cadastros/alarme'
    | '/app/cadastros/cerca'
    | '/app/cadastros/combustivel'
    | '/app/cadastros/dispositivos'
    | '/app/cadastros/equipamentos'
    | '/app/cadastros/garagens'
    | '/app/cadastros/grupos'
    | '/app/cadastros/grupos-linhas'
    | '/app/cadastros/linhas'
    | '/app/cadastros/pontos'
    | '/app/cadastros/pontos-interesse'
    | '/app/cadastros/unidades'
    | '/app/cadastros/usuarios'
    | '/app/cadastros/veiculos'
    | '/app/fretamento/assentos'
    | '/app/fretamento/cadastro-passageiros'
    | '/app/fretamento/centros-custo'
    | '/app/fretamento/escala'
    | '/app/fretamento/passageiros'
    | '/app/fretamento/ponto'
    | '/app/fretamento/rotas'
    | '/app/fretamento/roteirizacao'
    | '/app/fretamento/turnos'
    | '/app/frota/analise'
    | '/app/frota/checklist'
    | '/app/frota/combustivel'
    | '/app/frota/desempenho'
    | '/app/frota/diagnostico'
    | '/app/frota/manutencao'
    | '/app/frota/ordens'
    | '/app/frota/pneus'
    | '/app/frota/regeneracao'
    | '/app/frota/sinais'
    | '/app/frota/telemetria'
    | '/app/frota/tracking'
    | '/app/gerencial/indicadores'
    | '/app/gerencial/operacional'
    | '/app/manutencao/diagnostico'
    | '/app/manutencao/ordens'
    | '/app/manutencao/pneus'
    | '/app/manutencao/regeneracao'
    | '/app/motoristas/novo'
    | '/app/operacao/sinotico'
    | '/app/operacao/viagens'
    | '/app/pessoas/jornada'
    | '/app/pessoas/multas'
    | '/app/premiacao/metas'
    | '/app/relatorios/operacionais'
    | '/app/relatorios/telemetria'
    | '/app/seguranca/video'
    | '/app/urbano/padrao'
    | '/app/urbano/passageiros'
    | '/app/veiculos/novo'
    | '/app/manutencao/'
    | '/app/motoristas/'
    | '/app/premiacao/'
    | '/app/veiculos/'
    | '/app/fretamento/viagens/nova'
    | '/app/motoristas/perfil/$nome'
    | '/app/fretamento/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/login'
    | '/app/$'
    | '/app/assistente'
    | '/app/auditoria'
    | '/app/co2'
    | '/app/escala-viagem'
    | '/app/estrategico'
    | '/app/eventos'
    | '/app/gerencial'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app/suporte'
    | '/console/acessos'
    | '/console/administradores'
    | '/console/auditoria'
    | '/console/catalogo'
    | '/console/configuracoes'
    | '/console/contratos'
    | '/console/estoque'
    | '/console/indicadores'
    | '/console/perfis'
    | '/app'
    | '/console'
    | '/app/admin/catalogo'
    | '/app/admin/configuracoes'
    | '/app/admin/contratos'
    | '/app/cadastros/alarme'
    | '/app/cadastros/cerca'
    | '/app/cadastros/combustivel'
    | '/app/cadastros/dispositivos'
    | '/app/cadastros/equipamentos'
    | '/app/cadastros/garagens'
    | '/app/cadastros/grupos'
    | '/app/cadastros/grupos-linhas'
    | '/app/cadastros/linhas'
    | '/app/cadastros/pontos'
    | '/app/cadastros/pontos-interesse'
    | '/app/cadastros/unidades'
    | '/app/cadastros/usuarios'
    | '/app/cadastros/veiculos'
    | '/app/fretamento/assentos'
    | '/app/fretamento/cadastro-passageiros'
    | '/app/fretamento/centros-custo'
    | '/app/fretamento/escala'
    | '/app/fretamento/passageiros'
    | '/app/fretamento/ponto'
    | '/app/fretamento/rotas'
    | '/app/fretamento/roteirizacao'
    | '/app/fretamento/turnos'
    | '/app/frota/analise'
    | '/app/frota/checklist'
    | '/app/frota/combustivel'
    | '/app/frota/desempenho'
    | '/app/frota/diagnostico'
    | '/app/frota/manutencao'
    | '/app/frota/ordens'
    | '/app/frota/pneus'
    | '/app/frota/regeneracao'
    | '/app/frota/sinais'
    | '/app/frota/telemetria'
    | '/app/frota/tracking'
    | '/app/gerencial/indicadores'
    | '/app/gerencial/operacional'
    | '/app/manutencao/diagnostico'
    | '/app/manutencao/ordens'
    | '/app/manutencao/pneus'
    | '/app/manutencao/regeneracao'
    | '/app/motoristas/novo'
    | '/app/operacao/sinotico'
    | '/app/operacao/viagens'
    | '/app/pessoas/jornada'
    | '/app/pessoas/multas'
    | '/app/premiacao/metas'
    | '/app/relatorios/operacionais'
    | '/app/relatorios/telemetria'
    | '/app/seguranca/video'
    | '/app/urbano/padrao'
    | '/app/urbano/passageiros'
    | '/app/veiculos/novo'
    | '/app/manutencao'
    | '/app/motoristas'
    | '/app/premiacao'
    | '/app/veiculos'
    | '/app/fretamento/viagens/nova'
    | '/app/motoristas/perfil/$nome'
    | '/app/fretamento/viagens'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/console'
    | '/embed'
    | '/login'
    | '/app/$'
    | '/app/assistente'
    | '/app/auditoria'
    | '/app/co2'
    | '/app/escala-viagem'
    | '/app/estrategico'
    | '/app/eventos'
    | '/app/gerencial'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app/suporte'
    | '/console/acessos'
    | '/console/administradores'
    | '/console/auditoria'
    | '/console/catalogo'
    | '/console/configuracoes'
    | '/console/contratos'
    | '/console/estoque'
    | '/console/indicadores'
    | '/console/perfis'
    | '/app/'
    | '/console/'
    | '/app/admin/catalogo'
    | '/app/admin/configuracoes'
    | '/app/admin/contratos'
    | '/app/cadastros/alarme'
    | '/app/cadastros/cerca'
    | '/app/cadastros/combustivel'
    | '/app/cadastros/dispositivos'
    | '/app/cadastros/equipamentos'
    | '/app/cadastros/garagens'
    | '/app/cadastros/grupos'
    | '/app/cadastros/grupos-linhas'
    | '/app/cadastros/linhas'
    | '/app/cadastros/pontos'
    | '/app/cadastros/pontos-interesse'
    | '/app/cadastros/unidades'
    | '/app/cadastros/usuarios'
    | '/app/cadastros/veiculos'
    | '/app/fretamento/assentos'
    | '/app/fretamento/cadastro-passageiros'
    | '/app/fretamento/centros-custo'
    | '/app/fretamento/escala'
    | '/app/fretamento/passageiros'
    | '/app/fretamento/ponto'
    | '/app/fretamento/rotas'
    | '/app/fretamento/roteirizacao'
    | '/app/fretamento/turnos'
    | '/app/frota/analise'
    | '/app/frota/checklist'
    | '/app/frota/combustivel'
    | '/app/frota/desempenho'
    | '/app/frota/diagnostico'
    | '/app/frota/manutencao'
    | '/app/frota/ordens'
    | '/app/frota/pneus'
    | '/app/frota/regeneracao'
    | '/app/frota/sinais'
    | '/app/frota/telemetria'
    | '/app/frota/tracking'
    | '/app/gerencial/indicadores'
    | '/app/gerencial/operacional'
    | '/app/manutencao/diagnostico'
    | '/app/manutencao/ordens'
    | '/app/manutencao/pneus'
    | '/app/manutencao/regeneracao'
    | '/app/motoristas/novo'
    | '/app/operacao/sinotico'
    | '/app/operacao/viagens'
    | '/app/pessoas/jornada'
    | '/app/pessoas/multas'
    | '/app/premiacao/metas'
    | '/app/relatorios/operacionais'
    | '/app/relatorios/telemetria'
    | '/app/seguranca/video'
    | '/app/urbano/padrao'
    | '/app/urbano/passageiros'
    | '/app/veiculos/novo'
    | '/app/manutencao/'
    | '/app/motoristas/'
    | '/app/premiacao/'
    | '/app/veiculos/'
    | '/app/fretamento/viagens/nova'
    | '/app/motoristas/perfil/$nome'
    | '/app/fretamento/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConsoleRoute: typeof ConsoleRouteWithChildren
  EmbedRoute: typeof EmbedRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistente': {
      id: '/app/assistente'
      path: '/assistente'
      fullPath: '/app/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/co2': {
      id: '/app/co2'
      path: '/co2'
      fullPath: '/app/co2'
      preLoaderRoute: typeof AppCo2RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escala-viagem': {
      id: '/app/escala-viagem'
      path: '/escala-viagem'
      fullPath: '/app/escala-viagem'
      preLoaderRoute: typeof AppEscalaViagemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estrategico': {
      id: '/app/estrategico'
      path: '/estrategico'
      fullPath: '/app/estrategico'
      preLoaderRoute: typeof AppEstrategicoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/eventos': {
      id: '/app/eventos'
      path: '/eventos'
      fullPath: '/app/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gerencial': {
      id: '/app/gerencial'
      path: '/gerencial'
      fullPath: '/app/gerencial'
      preLoaderRoute: typeof AppGerencialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mapa': {
      id: '/app/mapa'
      path: '/mapa'
      fullPath: '/app/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/acessos': {
      id: '/console/acessos'
      path: '/acessos'
      fullPath: '/console/acessos'
      preLoaderRoute: typeof ConsoleAcessosRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/administradores': {
      id: '/console/administradores'
      path: '/administradores'
      fullPath: '/console/administradores'
      preLoaderRoute: typeof ConsoleAdministradoresRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/auditoria': {
      id: '/console/auditoria'
      path: '/auditoria'
      fullPath: '/console/auditoria'
      preLoaderRoute: typeof ConsoleAuditoriaRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/catalogo': {
      id: '/console/catalogo'
      path: '/catalogo'
      fullPath: '/console/catalogo'
      preLoaderRoute: typeof ConsoleCatalogoRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/configuracoes': {
      id: '/console/configuracoes'
      path: '/configuracoes'
      fullPath: '/console/configuracoes'
      preLoaderRoute: typeof ConsoleConfiguracoesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/contratos': {
      id: '/console/contratos'
      path: '/contratos'
      fullPath: '/console/contratos'
      preLoaderRoute: typeof ConsoleContratosRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/estoque': {
      id: '/console/estoque'
      path: '/estoque'
      fullPath: '/console/estoque'
      preLoaderRoute: typeof ConsoleEstoqueRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/indicadores': {
      id: '/console/indicadores'
      path: '/indicadores'
      fullPath: '/console/indicadores'
      preLoaderRoute: typeof ConsoleIndicadoresRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/perfis': {
      id: '/console/perfis'
      path: '/perfis'
      fullPath: '/console/perfis'
      preLoaderRoute: typeof ConsolePerfisRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/app/admin/catalogo': {
      id: '/app/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/app/admin/catalogo'
      preLoaderRoute: typeof AppAdminCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/configuracoes': {
      id: '/app/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/app/admin/configuracoes'
      preLoaderRoute: typeof AppAdminConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/contratos': {
      id: '/app/admin/contratos'
      path: '/admin/contratos'
      fullPath: '/app/admin/contratos'
      preLoaderRoute: typeof AppAdminContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/alarme': {
      id: '/app/cadastros/alarme'
      path: '/cadastros/alarme'
      fullPath: '/app/cadastros/alarme'
      preLoaderRoute: typeof AppCadastrosAlarmeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/cerca': {
      id: '/app/cadastros/cerca'
      path: '/cadastros/cerca'
      fullPath: '/app/cadastros/cerca'
      preLoaderRoute: typeof AppCadastrosCercaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/combustivel': {
      id: '/app/cadastros/combustivel'
      path: '/cadastros/combustivel'
      fullPath: '/app/cadastros/combustivel'
      preLoaderRoute: typeof AppCadastrosCombustivelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/dispositivos': {
      id: '/app/cadastros/dispositivos'
      path: '/cadastros/dispositivos'
      fullPath: '/app/cadastros/dispositivos'
      preLoaderRoute: typeof AppCadastrosDispositivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/equipamentos': {
      id: '/app/cadastros/equipamentos'
      path: '/cadastros/equipamentos'
      fullPath: '/app/cadastros/equipamentos'
      preLoaderRoute: typeof AppCadastrosEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/garagens': {
      id: '/app/cadastros/garagens'
      path: '/cadastros/garagens'
      fullPath: '/app/cadastros/garagens'
      preLoaderRoute: typeof AppCadastrosGaragensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/grupos': {
      id: '/app/cadastros/grupos'
      path: '/cadastros/grupos'
      fullPath: '/app/cadastros/grupos'
      preLoaderRoute: typeof AppCadastrosGruposRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/grupos-linhas': {
      id: '/app/cadastros/grupos-linhas'
      path: '/cadastros/grupos-linhas'
      fullPath: '/app/cadastros/grupos-linhas'
      preLoaderRoute: typeof AppCadastrosGruposLinhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/linhas': {
      id: '/app/cadastros/linhas'
      path: '/cadastros/linhas'
      fullPath: '/app/cadastros/linhas'
      preLoaderRoute: typeof AppCadastrosLinhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/pontos': {
      id: '/app/cadastros/pontos'
      path: '/cadastros/pontos'
      fullPath: '/app/cadastros/pontos'
      preLoaderRoute: typeof AppCadastrosPontosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/pontos-interesse': {
      id: '/app/cadastros/pontos-interesse'
      path: '/cadastros/pontos-interesse'
      fullPath: '/app/cadastros/pontos-interesse'
      preLoaderRoute: typeof AppCadastrosPontosInteresseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/unidades': {
      id: '/app/cadastros/unidades'
      path: '/cadastros/unidades'
      fullPath: '/app/cadastros/unidades'
      preLoaderRoute: typeof AppCadastrosUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/usuarios': {
      id: '/app/cadastros/usuarios'
      path: '/cadastros/usuarios'
      fullPath: '/app/cadastros/usuarios'
      preLoaderRoute: typeof AppCadastrosUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/veiculos': {
      id: '/app/cadastros/veiculos'
      path: '/cadastros/veiculos'
      fullPath: '/app/cadastros/veiculos'
      preLoaderRoute: typeof AppCadastrosVeiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/assentos': {
      id: '/app/fretamento/assentos'
      path: '/fretamento/assentos'
      fullPath: '/app/fretamento/assentos'
      preLoaderRoute: typeof AppFretamentoAssentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/cadastro-passageiros': {
      id: '/app/fretamento/cadastro-passageiros'
      path: '/fretamento/cadastro-passageiros'
      fullPath: '/app/fretamento/cadastro-passageiros'
      preLoaderRoute: typeof AppFretamentoCadastroPassageirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/centros-custo': {
      id: '/app/fretamento/centros-custo'
      path: '/fretamento/centros-custo'
      fullPath: '/app/fretamento/centros-custo'
      preLoaderRoute: typeof AppFretamentoCentrosCustoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/escala': {
      id: '/app/fretamento/escala'
      path: '/fretamento/escala'
      fullPath: '/app/fretamento/escala'
      preLoaderRoute: typeof AppFretamentoEscalaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/passageiros': {
      id: '/app/fretamento/passageiros'
      path: '/fretamento/passageiros'
      fullPath: '/app/fretamento/passageiros'
      preLoaderRoute: typeof AppFretamentoPassageirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/ponto': {
      id: '/app/fretamento/ponto'
      path: '/fretamento/ponto'
      fullPath: '/app/fretamento/ponto'
      preLoaderRoute: typeof AppFretamentoPontoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/rotas': {
      id: '/app/fretamento/rotas'
      path: '/fretamento/rotas'
      fullPath: '/app/fretamento/rotas'
      preLoaderRoute: typeof AppFretamentoRotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/roteirizacao': {
      id: '/app/fretamento/roteirizacao'
      path: '/fretamento/roteirizacao'
      fullPath: '/app/fretamento/roteirizacao'
      preLoaderRoute: typeof AppFretamentoRoteirizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/turnos': {
      id: '/app/fretamento/turnos'
      path: '/fretamento/turnos'
      fullPath: '/app/fretamento/turnos'
      preLoaderRoute: typeof AppFretamentoTurnosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/analise': {
      id: '/app/frota/analise'
      path: '/frota/analise'
      fullPath: '/app/frota/analise'
      preLoaderRoute: typeof AppFrotaAnaliseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/checklist': {
      id: '/app/frota/checklist'
      path: '/frota/checklist'
      fullPath: '/app/frota/checklist'
      preLoaderRoute: typeof AppFrotaChecklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/combustivel': {
      id: '/app/frota/combustivel'
      path: '/frota/combustivel'
      fullPath: '/app/frota/combustivel'
      preLoaderRoute: typeof AppFrotaCombustivelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/desempenho': {
      id: '/app/frota/desempenho'
      path: '/frota/desempenho'
      fullPath: '/app/frota/desempenho'
      preLoaderRoute: typeof AppFrotaDesempenhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/diagnostico': {
      id: '/app/frota/diagnostico'
      path: '/frota/diagnostico'
      fullPath: '/app/frota/diagnostico'
      preLoaderRoute: typeof AppFrotaDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/manutencao': {
      id: '/app/frota/manutencao'
      path: '/frota/manutencao'
      fullPath: '/app/frota/manutencao'
      preLoaderRoute: typeof AppFrotaManutencaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/ordens': {
      id: '/app/frota/ordens'
      path: '/frota/ordens'
      fullPath: '/app/frota/ordens'
      preLoaderRoute: typeof AppFrotaOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/pneus': {
      id: '/app/frota/pneus'
      path: '/frota/pneus'
      fullPath: '/app/frota/pneus'
      preLoaderRoute: typeof AppFrotaPneusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/regeneracao': {
      id: '/app/frota/regeneracao'
      path: '/frota/regeneracao'
      fullPath: '/app/frota/regeneracao'
      preLoaderRoute: typeof AppFrotaRegeneracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/sinais': {
      id: '/app/frota/sinais'
      path: '/frota/sinais'
      fullPath: '/app/frota/sinais'
      preLoaderRoute: typeof AppFrotaSinaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/telemetria': {
      id: '/app/frota/telemetria'
      path: '/frota/telemetria'
      fullPath: '/app/frota/telemetria'
      preLoaderRoute: typeof AppFrotaTelemetriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/tracking': {
      id: '/app/frota/tracking'
      path: '/frota/tracking'
      fullPath: '/app/frota/tracking'
      preLoaderRoute: typeof AppFrotaTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gerencial/indicadores': {
      id: '/app/gerencial/indicadores'
      path: '/indicadores'
      fullPath: '/app/gerencial/indicadores'
      preLoaderRoute: typeof AppGerencialIndicadoresRouteImport
      parentRoute: typeof AppGerencialRoute
    }
    '/app/gerencial/operacional': {
      id: '/app/gerencial/operacional'
      path: '/operacional'
      fullPath: '/app/gerencial/operacional'
      preLoaderRoute: typeof AppGerencialOperacionalRouteImport
      parentRoute: typeof AppGerencialRoute
    }
    '/app/manutencao/': {
      id: '/app/manutencao/'
      path: '/manutencao'
      fullPath: '/app/manutencao/'
      preLoaderRoute: typeof AppManutencaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manutencao/diagnostico': {
      id: '/app/manutencao/diagnostico'
      path: '/manutencao/diagnostico'
      fullPath: '/app/manutencao/diagnostico'
      preLoaderRoute: typeof AppManutencaoDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manutencao/ordens': {
      id: '/app/manutencao/ordens'
      path: '/manutencao/ordens'
      fullPath: '/app/manutencao/ordens'
      preLoaderRoute: typeof AppManutencaoOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manutencao/pneus': {
      id: '/app/manutencao/pneus'
      path: '/manutencao/pneus'
      fullPath: '/app/manutencao/pneus'
      preLoaderRoute: typeof AppManutencaoPneusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manutencao/regeneracao': {
      id: '/app/manutencao/regeneracao'
      path: '/manutencao/regeneracao'
      fullPath: '/app/manutencao/regeneracao'
      preLoaderRoute: typeof AppManutencaoRegeneracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/motoristas/': {
      id: '/app/motoristas/'
      path: '/motoristas'
      fullPath: '/app/motoristas/'
      preLoaderRoute: typeof AppMotoristasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/motoristas/novo': {
      id: '/app/motoristas/novo'
      path: '/motoristas/novo'
      fullPath: '/app/motoristas/novo'
      preLoaderRoute: typeof AppMotoristasNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operacao/sinotico': {
      id: '/app/operacao/sinotico'
      path: '/operacao/sinotico'
      fullPath: '/app/operacao/sinotico'
      preLoaderRoute: typeof AppOperacaoSinoticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operacao/viagens': {
      id: '/app/operacao/viagens'
      path: '/operacao/viagens'
      fullPath: '/app/operacao/viagens'
      preLoaderRoute: typeof AppOperacaoViagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pessoas/jornada': {
      id: '/app/pessoas/jornada'
      path: '/pessoas/jornada'
      fullPath: '/app/pessoas/jornada'
      preLoaderRoute: typeof AppPessoasJornadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pessoas/multas': {
      id: '/app/pessoas/multas'
      path: '/pessoas/multas'
      fullPath: '/app/pessoas/multas'
      preLoaderRoute: typeof AppPessoasMultasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premiacao/': {
      id: '/app/premiacao/'
      path: '/premiacao'
      fullPath: '/app/premiacao/'
      preLoaderRoute: typeof AppPremiacaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premiacao/metas': {
      id: '/app/premiacao/metas'
      path: '/premiacao/metas'
      fullPath: '/app/premiacao/metas'
      preLoaderRoute: typeof AppPremiacaoMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios/operacionais': {
      id: '/app/relatorios/operacionais'
      path: '/operacionais'
      fullPath: '/app/relatorios/operacionais'
      preLoaderRoute: typeof AppRelatoriosOperacionaisRouteImport
      parentRoute: typeof AppRelatoriosRoute
    }
    '/app/relatorios/telemetria': {
      id: '/app/relatorios/telemetria'
      path: '/telemetria'
      fullPath: '/app/relatorios/telemetria'
      preLoaderRoute: typeof AppRelatoriosTelemetriaRouteImport
      parentRoute: typeof AppRelatoriosRoute
    }
    '/app/seguranca/video': {
      id: '/app/seguranca/video'
      path: '/seguranca/video'
      fullPath: '/app/seguranca/video'
      preLoaderRoute: typeof AppSegurancaVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/urbano/padrao': {
      id: '/app/urbano/padrao'
      path: '/urbano/padrao'
      fullPath: '/app/urbano/padrao'
      preLoaderRoute: typeof AppUrbanoPadraoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/urbano/passageiros': {
      id: '/app/urbano/passageiros'
      path: '/urbano/passageiros'
      fullPath: '/app/urbano/passageiros'
      preLoaderRoute: typeof AppUrbanoPassageirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/': {
      id: '/app/veiculos/'
      path: '/veiculos'
      fullPath: '/app/veiculos/'
      preLoaderRoute: typeof AppVeiculosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/novo': {
      id: '/app/veiculos/novo'
      path: '/veiculos/novo'
      fullPath: '/app/veiculos/novo'
      preLoaderRoute: typeof AppVeiculosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/viagens/': {
      id: '/app/fretamento/viagens/'
      path: '/fretamento/viagens'
      fullPath: '/app/fretamento/viagens/'
      preLoaderRoute: typeof AppFretamentoViagensIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/viagens/nova': {
      id: '/app/fretamento/viagens/nova'
      path: '/fretamento/viagens/nova'
      fullPath: '/app/fretamento/viagens/nova'
      preLoaderRoute: typeof AppFretamentoViagensNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/motoristas/perfil/$nome': {
      id: '/app/motoristas/perfil/$nome'
      path: '/motoristas/perfil/$nome'
      fullPath: '/app/motoristas/perfil/$nome'
      preLoaderRoute: typeof AppMotoristasPerfilNomeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppGerencialRouteChildren {
  AppGerencialIndicadoresRoute: typeof AppGerencialIndicadoresRoute
  AppGerencialOperacionalRoute: typeof AppGerencialOperacionalRoute
}

const AppGerencialRouteChildren: AppGerencialRouteChildren = {
  AppGerencialIndicadoresRoute: AppGerencialIndicadoresRoute,
  AppGerencialOperacionalRoute: AppGerencialOperacionalRoute,
}

const AppGerencialRouteWithChildren = AppGerencialRoute._addFileChildren(
  AppGerencialRouteChildren,
)

interface AppRelatoriosRouteChildren {
  AppRelatoriosOperacionaisRoute: typeof AppRelatoriosOperacionaisRoute
  AppRelatoriosTelemetriaRoute: typeof AppRelatoriosTelemetriaRoute
}

const AppRelatoriosRouteChildren: AppRelatoriosRouteChildren = {
  AppRelatoriosOperacionaisRoute: AppRelatoriosOperacionaisRoute,
  AppRelatoriosTelemetriaRoute: AppRelatoriosTelemetriaRoute,
}

const AppRelatoriosRouteWithChildren = AppRelatoriosRoute._addFileChildren(
  AppRelatoriosRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCo2Route: typeof AppCo2Route
  AppEscalaViagemRoute: typeof AppEscalaViagemRoute
  AppEstrategicoRoute: typeof AppEstrategicoRoute
  AppEventosRoute: typeof AppEventosRoute
  AppGerencialRoute: typeof AppGerencialRouteWithChildren
  AppMapaRoute: typeof AppMapaRoute
  AppRelatoriosRoute: typeof AppRelatoriosRouteWithChildren
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminCatalogoRoute: typeof AppAdminCatalogoRoute
  AppAdminConfiguracoesRoute: typeof AppAdminConfiguracoesRoute
  AppAdminContratosRoute: typeof AppAdminContratosRoute
  AppCadastrosAlarmeRoute: typeof AppCadastrosAlarmeRoute
  AppCadastrosCercaRoute: typeof AppCadastrosCercaRoute
  AppCadastrosCombustivelRoute: typeof AppCadastrosCombustivelRoute
  AppCadastrosDispositivosRoute: typeof AppCadastrosDispositivosRoute
  AppCadastrosEquipamentosRoute: typeof AppCadastrosEquipamentosRoute
  AppCadastrosGaragensRoute: typeof AppCadastrosGaragensRoute
  AppCadastrosGruposRoute: typeof AppCadastrosGruposRoute
  AppCadastrosGruposLinhasRoute: typeof AppCadastrosGruposLinhasRoute
  AppCadastrosLinhasRoute: typeof AppCadastrosLinhasRoute
  AppCadastrosPontosRoute: typeof AppCadastrosPontosRoute
  AppCadastrosPontosInteresseRoute: typeof AppCadastrosPontosInteresseRoute
  AppCadastrosUnidadesRoute: typeof AppCadastrosUnidadesRoute
  AppCadastrosUsuariosRoute: typeof AppCadastrosUsuariosRoute
  AppCadastrosVeiculosRoute: typeof AppCadastrosVeiculosRoute
  AppFretamentoAssentosRoute: typeof AppFretamentoAssentosRoute
  AppFretamentoCadastroPassageirosRoute: typeof AppFretamentoCadastroPassageirosRoute
  AppFretamentoCentrosCustoRoute: typeof AppFretamentoCentrosCustoRoute
  AppFretamentoEscalaRoute: typeof AppFretamentoEscalaRoute
  AppFretamentoPassageirosRoute: typeof AppFretamentoPassageirosRoute
  AppFretamentoPontoRoute: typeof AppFretamentoPontoRoute
  AppFretamentoRotasRoute: typeof AppFretamentoRotasRoute
  AppFretamentoRoteirizacaoRoute: typeof AppFretamentoRoteirizacaoRoute
  AppFretamentoTurnosRoute: typeof AppFretamentoTurnosRoute
  AppFrotaAnaliseRoute: typeof AppFrotaAnaliseRoute
  AppFrotaChecklistRoute: typeof AppFrotaChecklistRoute
  AppFrotaCombustivelRoute: typeof AppFrotaCombustivelRoute
  AppFrotaDesempenhoRoute: typeof AppFrotaDesempenhoRoute
  AppFrotaDiagnosticoRoute: typeof AppFrotaDiagnosticoRoute
  AppFrotaManutencaoRoute: typeof AppFrotaManutencaoRoute
  AppFrotaOrdensRoute: typeof AppFrotaOrdensRoute
  AppFrotaPneusRoute: typeof AppFrotaPneusRoute
  AppFrotaRegeneracaoRoute: typeof AppFrotaRegeneracaoRoute
  AppFrotaSinaisRoute: typeof AppFrotaSinaisRoute
  AppFrotaTelemetriaRoute: typeof AppFrotaTelemetriaRoute
  AppFrotaTrackingRoute: typeof AppFrotaTrackingRoute
  AppManutencaoDiagnosticoRoute: typeof AppManutencaoDiagnosticoRoute
  AppManutencaoOrdensRoute: typeof AppManutencaoOrdensRoute
  AppManutencaoPneusRoute: typeof AppManutencaoPneusRoute
  AppManutencaoRegeneracaoRoute: typeof AppManutencaoRegeneracaoRoute
  AppMotoristasNovoRoute: typeof AppMotoristasNovoRoute
  AppOperacaoSinoticoRoute: typeof AppOperacaoSinoticoRoute
  AppOperacaoViagensRoute: typeof AppOperacaoViagensRoute
  AppPessoasJornadaRoute: typeof AppPessoasJornadaRoute
  AppPessoasMultasRoute: typeof AppPessoasMultasRoute
  AppPremiacaoMetasRoute: typeof AppPremiacaoMetasRoute
  AppSegurancaVideoRoute: typeof AppSegurancaVideoRoute
  AppUrbanoPadraoRoute: typeof AppUrbanoPadraoRoute
  AppUrbanoPassageirosRoute: typeof AppUrbanoPassageirosRoute
  AppVeiculosNovoRoute: typeof AppVeiculosNovoRoute
  AppManutencaoIndexRoute: typeof AppManutencaoIndexRoute
  AppMotoristasIndexRoute: typeof AppMotoristasIndexRoute
  AppPremiacaoIndexRoute: typeof AppPremiacaoIndexRoute
  AppVeiculosIndexRoute: typeof AppVeiculosIndexRoute
  AppFretamentoViagensNovaRoute: typeof AppFretamentoViagensNovaRoute
  AppMotoristasPerfilNomeRoute: typeof AppMotoristasPerfilNomeRoute
  AppFretamentoViagensIndexRoute: typeof AppFretamentoViagensIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAssistenteRoute: AppAssistenteRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCo2Route: AppCo2Route,
  AppEscalaViagemRoute: AppEscalaViagemRoute,
  AppEstrategicoRoute: AppEstrategicoRoute,
  AppEventosRoute: AppEventosRoute,
  AppGerencialRoute: AppGerencialRouteWithChildren,
  AppMapaRoute: AppMapaRoute,
  AppRelatoriosRoute: AppRelatoriosRouteWithChildren,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminCatalogoRoute: AppAdminCatalogoRoute,
  AppAdminConfiguracoesRoute: AppAdminConfiguracoesRoute,
  AppAdminContratosRoute: AppAdminContratosRoute,
  AppCadastrosAlarmeRoute: AppCadastrosAlarmeRoute,
  AppCadastrosCercaRoute: AppCadastrosCercaRoute,
  AppCadastrosCombustivelRoute: AppCadastrosCombustivelRoute,
  AppCadastrosDispositivosRoute: AppCadastrosDispositivosRoute,
  AppCadastrosEquipamentosRoute: AppCadastrosEquipamentosRoute,
  AppCadastrosGaragensRoute: AppCadastrosGaragensRoute,
  AppCadastrosGruposRoute: AppCadastrosGruposRoute,
  AppCadastrosGruposLinhasRoute: AppCadastrosGruposLinhasRoute,
  AppCadastrosLinhasRoute: AppCadastrosLinhasRoute,
  AppCadastrosPontosRoute: AppCadastrosPontosRoute,
  AppCadastrosPontosInteresseRoute: AppCadastrosPontosInteresseRoute,
  AppCadastrosUnidadesRoute: AppCadastrosUnidadesRoute,
  AppCadastrosUsuariosRoute: AppCadastrosUsuariosRoute,
  AppCadastrosVeiculosRoute: AppCadastrosVeiculosRoute,
  AppFretamentoAssentosRoute: AppFretamentoAssentosRoute,
  AppFretamentoCadastroPassageirosRoute: AppFretamentoCadastroPassageirosRoute,
  AppFretamentoCentrosCustoRoute: AppFretamentoCentrosCustoRoute,
  AppFretamentoEscalaRoute: AppFretamentoEscalaRoute,
  AppFretamentoPassageirosRoute: AppFretamentoPassageirosRoute,
  AppFretamentoPontoRoute: AppFretamentoPontoRoute,
  AppFretamentoRotasRoute: AppFretamentoRotasRoute,
  AppFretamentoRoteirizacaoRoute: AppFretamentoRoteirizacaoRoute,
  AppFretamentoTurnosRoute: AppFretamentoTurnosRoute,
  AppFrotaAnaliseRoute: AppFrotaAnaliseRoute,
  AppFrotaChecklistRoute: AppFrotaChecklistRoute,
  AppFrotaCombustivelRoute: AppFrotaCombustivelRoute,
  AppFrotaDesempenhoRoute: AppFrotaDesempenhoRoute,
  AppFrotaDiagnosticoRoute: AppFrotaDiagnosticoRoute,
  AppFrotaManutencaoRoute: AppFrotaManutencaoRoute,
  AppFrotaOrdensRoute: AppFrotaOrdensRoute,
  AppFrotaPneusRoute: AppFrotaPneusRoute,
  AppFrotaRegeneracaoRoute: AppFrotaRegeneracaoRoute,
  AppFrotaSinaisRoute: AppFrotaSinaisRoute,
  AppFrotaTelemetriaRoute: AppFrotaTelemetriaRoute,
  AppFrotaTrackingRoute: AppFrotaTrackingRoute,
  AppManutencaoDiagnosticoRoute: AppManutencaoDiagnosticoRoute,
  AppManutencaoOrdensRoute: AppManutencaoOrdensRoute,
  AppManutencaoPneusRoute: AppManutencaoPneusRoute,
  AppManutencaoRegeneracaoRoute: AppManutencaoRegeneracaoRoute,
  AppMotoristasNovoRoute: AppMotoristasNovoRoute,
  AppOperacaoSinoticoRoute: AppOperacaoSinoticoRoute,
  AppOperacaoViagensRoute: AppOperacaoViagensRoute,
  AppPessoasJornadaRoute: AppPessoasJornadaRoute,
  AppPessoasMultasRoute: AppPessoasMultasRoute,
  AppPremiacaoMetasRoute: AppPremiacaoMetasRoute,
  AppSegurancaVideoRoute: AppSegurancaVideoRoute,
  AppUrbanoPadraoRoute: AppUrbanoPadraoRoute,
  AppUrbanoPassageirosRoute: AppUrbanoPassageirosRoute,
  AppVeiculosNovoRoute: AppVeiculosNovoRoute,
  AppManutencaoIndexRoute: AppManutencaoIndexRoute,
  AppMotoristasIndexRoute: AppMotoristasIndexRoute,
  AppPremiacaoIndexRoute: AppPremiacaoIndexRoute,
  AppVeiculosIndexRoute: AppVeiculosIndexRoute,
  AppFretamentoViagensNovaRoute: AppFretamentoViagensNovaRoute,
  AppMotoristasPerfilNomeRoute: AppMotoristasPerfilNomeRoute,
  AppFretamentoViagensIndexRoute: AppFretamentoViagensIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ConsoleRouteChildren {
  ConsoleAcessosRoute: typeof ConsoleAcessosRoute
  ConsoleAdministradoresRoute: typeof ConsoleAdministradoresRoute
  ConsoleAuditoriaRoute: typeof ConsoleAuditoriaRoute
  ConsoleCatalogoRoute: typeof ConsoleCatalogoRoute
  ConsoleConfiguracoesRoute: typeof ConsoleConfiguracoesRoute
  ConsoleContratosRoute: typeof ConsoleContratosRoute
  ConsoleEstoqueRoute: typeof ConsoleEstoqueRoute
  ConsoleIndicadoresRoute: typeof ConsoleIndicadoresRoute
  ConsolePerfisRoute: typeof ConsolePerfisRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAcessosRoute: ConsoleAcessosRoute,
  ConsoleAdministradoresRoute: ConsoleAdministradoresRoute,
  ConsoleAuditoriaRoute: ConsoleAuditoriaRoute,
  ConsoleCatalogoRoute: ConsoleCatalogoRoute,
  ConsoleConfiguracoesRoute: ConsoleConfiguracoesRoute,
  ConsoleContratosRoute: ConsoleContratosRoute,
  ConsoleEstoqueRoute: ConsoleEstoqueRoute,
  ConsoleIndicadoresRoute: ConsoleIndicadoresRoute,
  ConsolePerfisRoute: ConsolePerfisRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConsoleRoute: ConsoleRouteWithChildren,
  EmbedRoute: EmbedRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
