/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppCo2RouteImport } from './routes/app.co2'
import { Route as AppEstrategicoRouteImport } from './routes/app.estrategico'
import { Route as AppEventosRouteImport } from './routes/app.eventos'
import { Route as AppMapaRouteImport } from './routes/app.mapa'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppCadastrosAlarmeRouteImport } from './routes/app.cadastros.alarme'
import { Route as AppCadastrosCercaRouteImport } from './routes/app.cadastros.cerca'
import { Route as AppCadastrosCombustivelRouteImport } from './routes/app.cadastros.combustivel'
import { Route as AppCadastrosDispositivosRouteImport } from './routes/app.cadastros.dispositivos'
import { Route as AppCadastrosGaragensRouteImport } from './routes/app.cadastros.garagens'
import { Route as AppCadastrosGruposRouteImport } from './routes/app.cadastros.grupos'
import { Route as AppCadastrosLinhasRouteImport } from './routes/app.cadastros.linhas'
import { Route as AppCadastrosPontosRouteImport } from './routes/app.cadastros.pontos'
import { Route as AppCadastrosUnidadesRouteImport } from './routes/app.cadastros.unidades'
import { Route as AppCadastrosUsuariosRouteImport } from './routes/app.cadastros.usuarios'
import { Route as AppFretamentoAssentosRouteImport } from './routes/app.fretamento.assentos'
import { Route as AppFretamentoContratosRouteImport } from './routes/app.fretamento.contratos'
import { Route as AppFretamentoEscalaRouteImport } from './routes/app.fretamento.escala'
import { Route as AppFretamentoPassageirosRouteImport } from './routes/app.fretamento.passageiros'
import { Route as AppFretamentoPontoRouteImport } from './routes/app.fretamento.ponto'
import { Route as AppFretamentoRoteirizacaoRouteImport } from './routes/app.fretamento.roteirizacao'
import { Route as AppFrotaAnaliseRouteImport } from './routes/app.frota.analise'
import { Route as AppFrotaDesempenhoRouteImport } from './routes/app.frota.desempenho'
import { Route as AppFrotaManutencaoRouteImport } from './routes/app.frota.manutencao'
import { Route as AppFrotaOrdensRouteImport } from './routes/app.frota.ordens'
import { Route as AppFrotaPneusRouteImport } from './routes/app.frota.pneus'
import { Route as AppFrotaRegeneracaoRouteImport } from './routes/app.frota.regeneracao'
import { Route as AppFrotaTelemetriaRouteImport } from './routes/app.frota.telemetria'
import { Route as AppGerencialIndicadoresRouteImport } from './routes/app.gerencial.indicadores'
import { Route as AppMotoristasIndexRouteImport } from './routes/app.motoristas.index'
import { Route as AppMotoristasNovoRouteImport } from './routes/app.motoristas.novo'
import { Route as AppOperacaoAlarmesRouteImport } from './routes/app.operacao.alarmes'
import { Route as AppOperacaoViagensRouteImport } from './routes/app.operacao.viagens'
import { Route as AppPessoasJornadaRouteImport } from './routes/app.pessoas.jornada'
import { Route as AppPremiacaoIndexRouteImport } from './routes/app.premiacao.index'
import { Route as AppPremiacaoMetasRouteImport } from './routes/app.premiacao.metas'
import { Route as AppSegurancaVideoRouteImport } from './routes/app.seguranca.video'
import { Route as AppVeiculosIndexRouteImport } from './routes/app.veiculos.index'
import { Route as AppVeiculosNovoRouteImport } from './routes/app.veiculos.novo'
import { Route as AppFretamentoViagensIndexRouteImport } from './routes/app.fretamento.viagens.index'
import { Route as AppFretamentoViagensNovaRouteImport } from './routes/app.fretamento.viagens.nova'
import { Route as AppMotoristasPerfilNomeRouteImport } from './routes/app.motoristas.perfil.$nome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppCo2Route = AppCo2RouteImport.update({
  id: '/co2',
  path: '/co2',
  getParentRoute: () => AppRoute,
} as any)
const AppEstrategicoRoute = AppEstrategicoRouteImport.update({
  id: '/estrategico',
  path: '/estrategico',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosAlarmeRoute = AppCadastrosAlarmeRouteImport.update({
  id: '/cadastros/alarme',
  path: '/cadastros/alarme',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosCercaRoute = AppCadastrosCercaRouteImport.update({
  id: '/cadastros/cerca',
  path: '/cadastros/cerca',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosCombustivelRoute = AppCadastrosCombustivelRouteImport.update({
  id: '/cadastros/combustivel',
  path: '/cadastros/combustivel',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosDispositivosRoute =
  AppCadastrosDispositivosRouteImport.update({
    id: '/cadastros/dispositivos',
    path: '/cadastros/dispositivos',
    getParentRoute: () => AppRoute,
  } as any)
const AppCadastrosGaragensRoute = AppCadastrosGaragensRouteImport.update({
  id: '/cadastros/garagens',
  path: '/cadastros/garagens',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosGruposRoute = AppCadastrosGruposRouteImport.update({
  id: '/cadastros/grupos',
  path: '/cadastros/grupos',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosLinhasRoute = AppCadastrosLinhasRouteImport.update({
  id: '/cadastros/linhas',
  path: '/cadastros/linhas',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosPontosRoute = AppCadastrosPontosRouteImport.update({
  id: '/cadastros/pontos',
  path: '/cadastros/pontos',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosUnidadesRoute = AppCadastrosUnidadesRouteImport.update({
  id: '/cadastros/unidades',
  path: '/cadastros/unidades',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosUsuariosRoute = AppCadastrosUsuariosRouteImport.update({
  id: '/cadastros/usuarios',
  path: '/cadastros/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoAssentosRoute = AppFretamentoAssentosRouteImport.update({
  id: '/fretamento/assentos',
  path: '/fretamento/assentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoContratosRoute = AppFretamentoContratosRouteImport.update({
  id: '/fretamento/contratos',
  path: '/fretamento/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoEscalaRoute = AppFretamentoEscalaRouteImport.update({
  id: '/fretamento/escala',
  path: '/fretamento/escala',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoPassageirosRoute =
  AppFretamentoPassageirosRouteImport.update({
    id: '/fretamento/passageiros',
    path: '/fretamento/passageiros',
    getParentRoute: () => AppRoute,
  } as any)
const AppFretamentoPontoRoute = AppFretamentoPontoRouteImport.update({
  id: '/fretamento/ponto',
  path: '/fretamento/ponto',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoRoteirizacaoRoute =
  AppFretamentoRoteirizacaoRouteImport.update({
    id: '/fretamento/roteirizacao',
    path: '/fretamento/roteirizacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppFrotaAnaliseRoute = AppFrotaAnaliseRouteImport.update({
  id: '/frota/analise',
  path: '/frota/analise',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaDesempenhoRoute = AppFrotaDesempenhoRouteImport.update({
  id: '/frota/desempenho',
  path: '/frota/desempenho',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaManutencaoRoute = AppFrotaManutencaoRouteImport.update({
  id: '/frota/manutencao',
  path: '/frota/manutencao',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaOrdensRoute = AppFrotaOrdensRouteImport.update({
  id: '/frota/ordens',
  path: '/frota/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaPneusRoute = AppFrotaPneusRouteImport.update({
  id: '/frota/pneus',
  path: '/frota/pneus',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaRegeneracaoRoute = AppFrotaRegeneracaoRouteImport.update({
  id: '/frota/regeneracao',
  path: '/frota/regeneracao',
  getParentRoute: () => AppRoute,
} as any)
const AppFrotaTelemetriaRoute = AppFrotaTelemetriaRouteImport.update({
  id: '/frota/telemetria',
  path: '/frota/telemetria',
  getParentRoute: () => AppRoute,
} as any)
const AppGerencialIndicadoresRoute = AppGerencialIndicadoresRouteImport.update({
  id: '/gerencial/indicadores',
  path: '/gerencial/indicadores',
  getParentRoute: () => AppRoute,
} as any)
const AppMotoristasIndexRoute = AppMotoristasIndexRouteImport.update({
  id: '/motoristas/',
  path: '/motoristas/',
  getParentRoute: () => AppRoute,
} as any)
const AppMotoristasNovoRoute = AppMotoristasNovoRouteImport.update({
  id: '/motoristas/novo',
  path: '/motoristas/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacaoAlarmesRoute = AppOperacaoAlarmesRouteImport.update({
  id: '/operacao/alarmes',
  path: '/operacao/alarmes',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacaoViagensRoute = AppOperacaoViagensRouteImport.update({
  id: '/operacao/viagens',
  path: '/operacao/viagens',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasJornadaRoute = AppPessoasJornadaRouteImport.update({
  id: '/pessoas/jornada',
  path: '/pessoas/jornada',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiacaoIndexRoute = AppPremiacaoIndexRouteImport.update({
  id: '/premiacao/',
  path: '/premiacao/',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiacaoMetasRoute = AppPremiacaoMetasRouteImport.update({
  id: '/premiacao/metas',
  path: '/premiacao/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppSegurancaVideoRoute = AppSegurancaVideoRouteImport.update({
  id: '/seguranca/video',
  path: '/seguranca/video',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosIndexRoute = AppVeiculosIndexRouteImport.update({
  id: '/veiculos/',
  path: '/veiculos/',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosNovoRoute = AppVeiculosNovoRouteImport.update({
  id: '/veiculos/novo',
  path: '/veiculos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppFretamentoViagensIndexRoute =
  AppFretamentoViagensIndexRouteImport.update({
    id: '/fretamento/viagens/',
    path: '/fretamento/viagens/',
    getParentRoute: () => AppRoute,
  } as any)
const AppFretamentoViagensNovaRoute =
  AppFretamentoViagensNovaRouteImport.update({
    id: '/fretamento/viagens/nova',
    path: '/fretamento/viagens/nova',
    getParentRoute: () => AppRoute,
  } as any)
const AppMotoristasPerfilNomeRoute = AppMotoristasPerfilNomeRouteImport.update({
  id: '/motoristas/perfil/$nome',
  path: '/motoristas/perfil/$nome',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/co2': typeof AppCo2Route
  '/app/estrategico': typeof AppEstrategicoRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/app/cadastros/alarme': typeof AppCadastrosAlarmeRoute
  '/app/cadastros/cerca': typeof AppCadastrosCercaRoute
  '/app/cadastros/combustivel': typeof AppCadastrosCombustivelRoute
  '/app/cadastros/dispositivos': typeof AppCadastrosDispositivosRoute
  '/app/cadastros/garagens': typeof AppCadastrosGaragensRoute
  '/app/cadastros/grupos': typeof AppCadastrosGruposRoute
  '/app/cadastros/linhas': typeof AppCadastrosLinhasRoute
  '/app/cadastros/pontos': typeof AppCadastrosPontosRoute
  '/app/cadastros/unidades': typeof AppCadastrosUnidadesRoute
  '/app/cadastros/usuarios': typeof AppCadastrosUsuariosRoute
  '/app/fretamento/assentos': typeof AppFretamentoAssentosRoute
  '/app/fretamento/contratos': typeof AppFretamentoContratosRoute
  '/app/fretamento/escala': typeof AppFretamentoEscalaRoute
  '/app/fretamento/passageiros': typeof AppFretamentoPassageirosRoute
  '/app/fretamento/ponto': typeof AppFretamentoPontoRoute
  '/app/fretamento/roteirizacao': typeof AppFretamentoRoteirizacaoRoute
  '/app/frota/analise': typeof AppFrotaAnaliseRoute
  '/app/frota/desempenho': typeof AppFrotaDesempenhoRoute
  '/app/frota/manutencao': typeof AppFrotaManutencaoRoute
  '/app/frota/ordens': typeof AppFrotaOrdensRoute
  '/app/frota/pneus': typeof AppFrotaPneusRoute
  '/app/frota/regeneracao': typeof AppFrotaRegeneracaoRoute
  '/app/frota/telemetria': typeof AppFrotaTelemetriaRoute
  '/app/gerencial/indicadores': typeof AppGerencialIndicadoresRoute
  '/app/motoristas/novo': typeof AppMotoristasNovoRoute
  '/app/operacao/alarmes': typeof AppOperacaoAlarmesRoute
  '/app/operacao/viagens': typeof AppOperacaoViagensRoute
  '/app/pessoas/jornada': typeof AppPessoasJornadaRoute
  '/app/premiacao/metas': typeof AppPremiacaoMetasRoute
  '/app/seguranca/video': typeof AppSegurancaVideoRoute
  '/app/veiculos/novo': typeof AppVeiculosNovoRoute
  '/app/motoristas/': typeof AppMotoristasIndexRoute
  '/app/premiacao/': typeof AppPremiacaoIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
  '/app/fretamento/viagens/nova': typeof AppFretamentoViagensNovaRoute
  '/app/motoristas/perfil/$nome': typeof AppMotoristasPerfilNomeRoute
  '/app/fretamento/viagens/': typeof AppFretamentoViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/co2': typeof AppCo2Route
  '/app/estrategico': typeof AppEstrategicoRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app': typeof AppIndexRoute
  '/app/cadastros/alarme': typeof AppCadastrosAlarmeRoute
  '/app/cadastros/cerca': typeof AppCadastrosCercaRoute
  '/app/cadastros/combustivel': typeof AppCadastrosCombustivelRoute
  '/app/cadastros/dispositivos': typeof AppCadastrosDispositivosRoute
  '/app/cadastros/garagens': typeof AppCadastrosGaragensRoute
  '/app/cadastros/grupos': typeof AppCadastrosGruposRoute
  '/app/cadastros/linhas': typeof AppCadastrosLinhasRoute
  '/app/cadastros/pontos': typeof AppCadastrosPontosRoute
  '/app/cadastros/unidades': typeof AppCadastrosUnidadesRoute
  '/app/cadastros/usuarios': typeof AppCadastrosUsuariosRoute
  '/app/fretamento/assentos': typeof AppFretamentoAssentosRoute
  '/app/fretamento/contratos': typeof AppFretamentoContratosRoute
  '/app/fretamento/escala': typeof AppFretamentoEscalaRoute
  '/app/fretamento/passageiros': typeof AppFretamentoPassageirosRoute
  '/app/fretamento/ponto': typeof AppFretamentoPontoRoute
  '/app/fretamento/roteirizacao': typeof AppFretamentoRoteirizacaoRoute
  '/app/frota/analise': typeof AppFrotaAnaliseRoute
  '/app/frota/desempenho': typeof AppFrotaDesempenhoRoute
  '/app/frota/manutencao': typeof AppFrotaManutencaoRoute
  '/app/frota/ordens': typeof AppFrotaOrdensRoute
  '/app/frota/pneus': typeof AppFrotaPneusRoute
  '/app/frota/regeneracao': typeof AppFrotaRegeneracaoRoute
  '/app/frota/telemetria': typeof AppFrotaTelemetriaRoute
  '/app/gerencial/indicadores': typeof AppGerencialIndicadoresRoute
  '/app/motoristas/novo': typeof AppMotoristasNovoRoute
  '/app/operacao/alarmes': typeof AppOperacaoAlarmesRoute
  '/app/operacao/viagens': typeof AppOperacaoViagensRoute
  '/app/pessoas/jornada': typeof AppPessoasJornadaRoute
  '/app/premiacao/metas': typeof AppPremiacaoMetasRoute
  '/app/seguranca/video': typeof AppSegurancaVideoRoute
  '/app/veiculos/novo': typeof AppVeiculosNovoRoute
  '/app/motoristas': typeof AppMotoristasIndexRoute
  '/app/premiacao': typeof AppPremiacaoIndexRoute
  '/app/veiculos': typeof AppVeiculosIndexRoute
  '/app/fretamento/viagens/nova': typeof AppFretamentoViagensNovaRoute
  '/app/motoristas/perfil/$nome': typeof AppMotoristasPerfilNomeRoute
  '/app/fretamento/viagens': typeof AppFretamentoViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$': typeof AppSplatRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/co2': typeof AppCo2Route
  '/app/estrategico': typeof AppEstrategicoRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/app/cadastros/alarme': typeof AppCadastrosAlarmeRoute
  '/app/cadastros/cerca': typeof AppCadastrosCercaRoute
  '/app/cadastros/combustivel': typeof AppCadastrosCombustivelRoute
  '/app/cadastros/dispositivos': typeof AppCadastrosDispositivosRoute
  '/app/cadastros/garagens': typeof AppCadastrosGaragensRoute
  '/app/cadastros/grupos': typeof AppCadastrosGruposRoute
  '/app/cadastros/linhas': typeof AppCadastrosLinhasRoute
  '/app/cadastros/pontos': typeof AppCadastrosPontosRoute
  '/app/cadastros/unidades': typeof AppCadastrosUnidadesRoute
  '/app/cadastros/usuarios': typeof AppCadastrosUsuariosRoute
  '/app/fretamento/assentos': typeof AppFretamentoAssentosRoute
  '/app/fretamento/contratos': typeof AppFretamentoContratosRoute
  '/app/fretamento/escala': typeof AppFretamentoEscalaRoute
  '/app/fretamento/passageiros': typeof AppFretamentoPassageirosRoute
  '/app/fretamento/ponto': typeof AppFretamentoPontoRoute
  '/app/fretamento/roteirizacao': typeof AppFretamentoRoteirizacaoRoute
  '/app/frota/analise': typeof AppFrotaAnaliseRoute
  '/app/frota/desempenho': typeof AppFrotaDesempenhoRoute
  '/app/frota/manutencao': typeof AppFrotaManutencaoRoute
  '/app/frota/ordens': typeof AppFrotaOrdensRoute
  '/app/frota/pneus': typeof AppFrotaPneusRoute
  '/app/frota/regeneracao': typeof AppFrotaRegeneracaoRoute
  '/app/frota/telemetria': typeof AppFrotaTelemetriaRoute
  '/app/gerencial/indicadores': typeof AppGerencialIndicadoresRoute
  '/app/motoristas/novo': typeof AppMotoristasNovoRoute
  '/app/operacao/alarmes': typeof AppOperacaoAlarmesRoute
  '/app/operacao/viagens': typeof AppOperacaoViagensRoute
  '/app/pessoas/jornada': typeof AppPessoasJornadaRoute
  '/app/premiacao/metas': typeof AppPremiacaoMetasRoute
  '/app/seguranca/video': typeof AppSegurancaVideoRoute
  '/app/veiculos/novo': typeof AppVeiculosNovoRoute
  '/app/motoristas/': typeof AppMotoristasIndexRoute
  '/app/premiacao/': typeof AppPremiacaoIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
  '/app/fretamento/viagens/nova': typeof AppFretamentoViagensNovaRoute
  '/app/motoristas/perfil/$nome': typeof AppMotoristasPerfilNomeRoute
  '/app/fretamento/viagens/': typeof AppFretamentoViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/$'
    | '/app/auditoria'
    | '/app/co2'
    | '/app/estrategico'
    | '/app/eventos'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app/'
    | '/app/cadastros/alarme'
    | '/app/cadastros/cerca'
    | '/app/cadastros/combustivel'
    | '/app/cadastros/dispositivos'
    | '/app/cadastros/garagens'
    | '/app/cadastros/grupos'
    | '/app/cadastros/linhas'
    | '/app/cadastros/pontos'
    | '/app/cadastros/unidades'
    | '/app/cadastros/usuarios'
    | '/app/fretamento/assentos'
    | '/app/fretamento/contratos'
    | '/app/fretamento/escala'
    | '/app/fretamento/passageiros'
    | '/app/fretamento/ponto'
    | '/app/fretamento/roteirizacao'
    | '/app/frota/analise'
    | '/app/frota/desempenho'
    | '/app/frota/manutencao'
    | '/app/frota/ordens'
    | '/app/frota/pneus'
    | '/app/frota/regeneracao'
    | '/app/frota/telemetria'
    | '/app/gerencial/indicadores'
    | '/app/motoristas/novo'
    | '/app/operacao/alarmes'
    | '/app/operacao/viagens'
    | '/app/pessoas/jornada'
    | '/app/premiacao/metas'
    | '/app/seguranca/video'
    | '/app/veiculos/novo'
    | '/app/motoristas/'
    | '/app/premiacao/'
    | '/app/veiculos/'
    | '/app/fretamento/viagens/nova'
    | '/app/motoristas/perfil/$nome'
    | '/app/fretamento/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/$'
    | '/app/auditoria'
    | '/app/co2'
    | '/app/estrategico'
    | '/app/eventos'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app'
    | '/app/cadastros/alarme'
    | '/app/cadastros/cerca'
    | '/app/cadastros/combustivel'
    | '/app/cadastros/dispositivos'
    | '/app/cadastros/garagens'
    | '/app/cadastros/grupos'
    | '/app/cadastros/linhas'
    | '/app/cadastros/pontos'
    | '/app/cadastros/unidades'
    | '/app/cadastros/usuarios'
    | '/app/fretamento/assentos'
    | '/app/fretamento/contratos'
    | '/app/fretamento/escala'
    | '/app/fretamento/passageiros'
    | '/app/fretamento/ponto'
    | '/app/fretamento/roteirizacao'
    | '/app/frota/analise'
    | '/app/frota/desempenho'
    | '/app/frota/manutencao'
    | '/app/frota/ordens'
    | '/app/frota/pneus'
    | '/app/frota/regeneracao'
    | '/app/frota/telemetria'
    | '/app/gerencial/indicadores'
    | '/app/motoristas/novo'
    | '/app/operacao/alarmes'
    | '/app/operacao/viagens'
    | '/app/pessoas/jornada'
    | '/app/premiacao/metas'
    | '/app/seguranca/video'
    | '/app/veiculos/novo'
    | '/app/motoristas'
    | '/app/premiacao'
    | '/app/veiculos'
    | '/app/fretamento/viagens/nova'
    | '/app/motoristas/perfil/$nome'
    | '/app/fretamento/viagens'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/$'
    | '/app/auditoria'
    | '/app/co2'
    | '/app/estrategico'
    | '/app/eventos'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app/'
    | '/app/cadastros/alarme'
    | '/app/cadastros/cerca'
    | '/app/cadastros/combustivel'
    | '/app/cadastros/dispositivos'
    | '/app/cadastros/garagens'
    | '/app/cadastros/grupos'
    | '/app/cadastros/linhas'
    | '/app/cadastros/pontos'
    | '/app/cadastros/unidades'
    | '/app/cadastros/usuarios'
    | '/app/fretamento/assentos'
    | '/app/fretamento/contratos'
    | '/app/fretamento/escala'
    | '/app/fretamento/passageiros'
    | '/app/fretamento/ponto'
    | '/app/fretamento/roteirizacao'
    | '/app/frota/analise'
    | '/app/frota/desempenho'
    | '/app/frota/manutencao'
    | '/app/frota/ordens'
    | '/app/frota/pneus'
    | '/app/frota/regeneracao'
    | '/app/frota/telemetria'
    | '/app/gerencial/indicadores'
    | '/app/motoristas/novo'
    | '/app/operacao/alarmes'
    | '/app/operacao/viagens'
    | '/app/pessoas/jornada'
    | '/app/premiacao/metas'
    | '/app/seguranca/video'
    | '/app/veiculos/novo'
    | '/app/motoristas/'
    | '/app/premiacao/'
    | '/app/veiculos/'
    | '/app/fretamento/viagens/nova'
    | '/app/motoristas/perfil/$nome'
    | '/app/fretamento/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/co2': {
      id: '/app/co2'
      path: '/co2'
      fullPath: '/app/co2'
      preLoaderRoute: typeof AppCo2RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estrategico': {
      id: '/app/estrategico'
      path: '/estrategico'
      fullPath: '/app/estrategico'
      preLoaderRoute: typeof AppEstrategicoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/eventos': {
      id: '/app/eventos'
      path: '/eventos'
      fullPath: '/app/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mapa': {
      id: '/app/mapa'
      path: '/mapa'
      fullPath: '/app/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/alarme': {
      id: '/app/cadastros/alarme'
      path: '/cadastros/alarme'
      fullPath: '/app/cadastros/alarme'
      preLoaderRoute: typeof AppCadastrosAlarmeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/cerca': {
      id: '/app/cadastros/cerca'
      path: '/cadastros/cerca'
      fullPath: '/app/cadastros/cerca'
      preLoaderRoute: typeof AppCadastrosCercaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/combustivel': {
      id: '/app/cadastros/combustivel'
      path: '/cadastros/combustivel'
      fullPath: '/app/cadastros/combustivel'
      preLoaderRoute: typeof AppCadastrosCombustivelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/dispositivos': {
      id: '/app/cadastros/dispositivos'
      path: '/cadastros/dispositivos'
      fullPath: '/app/cadastros/dispositivos'
      preLoaderRoute: typeof AppCadastrosDispositivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/garagens': {
      id: '/app/cadastros/garagens'
      path: '/cadastros/garagens'
      fullPath: '/app/cadastros/garagens'
      preLoaderRoute: typeof AppCadastrosGaragensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/grupos': {
      id: '/app/cadastros/grupos'
      path: '/cadastros/grupos'
      fullPath: '/app/cadastros/grupos'
      preLoaderRoute: typeof AppCadastrosGruposRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/linhas': {
      id: '/app/cadastros/linhas'
      path: '/cadastros/linhas'
      fullPath: '/app/cadastros/linhas'
      preLoaderRoute: typeof AppCadastrosLinhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/pontos': {
      id: '/app/cadastros/pontos'
      path: '/cadastros/pontos'
      fullPath: '/app/cadastros/pontos'
      preLoaderRoute: typeof AppCadastrosPontosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/unidades': {
      id: '/app/cadastros/unidades'
      path: '/cadastros/unidades'
      fullPath: '/app/cadastros/unidades'
      preLoaderRoute: typeof AppCadastrosUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/usuarios': {
      id: '/app/cadastros/usuarios'
      path: '/cadastros/usuarios'
      fullPath: '/app/cadastros/usuarios'
      preLoaderRoute: typeof AppCadastrosUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/assentos': {
      id: '/app/fretamento/assentos'
      path: '/fretamento/assentos'
      fullPath: '/app/fretamento/assentos'
      preLoaderRoute: typeof AppFretamentoAssentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/contratos': {
      id: '/app/fretamento/contratos'
      path: '/fretamento/contratos'
      fullPath: '/app/fretamento/contratos'
      preLoaderRoute: typeof AppFretamentoContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/escala': {
      id: '/app/fretamento/escala'
      path: '/fretamento/escala'
      fullPath: '/app/fretamento/escala'
      preLoaderRoute: typeof AppFretamentoEscalaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/passageiros': {
      id: '/app/fretamento/passageiros'
      path: '/fretamento/passageiros'
      fullPath: '/app/fretamento/passageiros'
      preLoaderRoute: typeof AppFretamentoPassageirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/ponto': {
      id: '/app/fretamento/ponto'
      path: '/fretamento/ponto'
      fullPath: '/app/fretamento/ponto'
      preLoaderRoute: typeof AppFretamentoPontoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/roteirizacao': {
      id: '/app/fretamento/roteirizacao'
      path: '/fretamento/roteirizacao'
      fullPath: '/app/fretamento/roteirizacao'
      preLoaderRoute: typeof AppFretamentoRoteirizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/analise': {
      id: '/app/frota/analise'
      path: '/frota/analise'
      fullPath: '/app/frota/analise'
      preLoaderRoute: typeof AppFrotaAnaliseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/desempenho': {
      id: '/app/frota/desempenho'
      path: '/frota/desempenho'
      fullPath: '/app/frota/desempenho'
      preLoaderRoute: typeof AppFrotaDesempenhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/manutencao': {
      id: '/app/frota/manutencao'
      path: '/frota/manutencao'
      fullPath: '/app/frota/manutencao'
      preLoaderRoute: typeof AppFrotaManutencaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/ordens': {
      id: '/app/frota/ordens'
      path: '/frota/ordens'
      fullPath: '/app/frota/ordens'
      preLoaderRoute: typeof AppFrotaOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/pneus': {
      id: '/app/frota/pneus'
      path: '/frota/pneus'
      fullPath: '/app/frota/pneus'
      preLoaderRoute: typeof AppFrotaPneusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/regeneracao': {
      id: '/app/frota/regeneracao'
      path: '/frota/regeneracao'
      fullPath: '/app/frota/regeneracao'
      preLoaderRoute: typeof AppFrotaRegeneracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frota/telemetria': {
      id: '/app/frota/telemetria'
      path: '/frota/telemetria'
      fullPath: '/app/frota/telemetria'
      preLoaderRoute: typeof AppFrotaTelemetriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gerencial/indicadores': {
      id: '/app/gerencial/indicadores'
      path: '/gerencial/indicadores'
      fullPath: '/app/gerencial/indicadores'
      preLoaderRoute: typeof AppGerencialIndicadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/motoristas/': {
      id: '/app/motoristas/'
      path: '/motoristas'
      fullPath: '/app/motoristas/'
      preLoaderRoute: typeof AppMotoristasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/motoristas/novo': {
      id: '/app/motoristas/novo'
      path: '/motoristas/novo'
      fullPath: '/app/motoristas/novo'
      preLoaderRoute: typeof AppMotoristasNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operacao/alarmes': {
      id: '/app/operacao/alarmes'
      path: '/operacao/alarmes'
      fullPath: '/app/operacao/alarmes'
      preLoaderRoute: typeof AppOperacaoAlarmesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operacao/viagens': {
      id: '/app/operacao/viagens'
      path: '/operacao/viagens'
      fullPath: '/app/operacao/viagens'
      preLoaderRoute: typeof AppOperacaoViagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pessoas/jornada': {
      id: '/app/pessoas/jornada'
      path: '/pessoas/jornada'
      fullPath: '/app/pessoas/jornada'
      preLoaderRoute: typeof AppPessoasJornadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premiacao/': {
      id: '/app/premiacao/'
      path: '/premiacao'
      fullPath: '/app/premiacao/'
      preLoaderRoute: typeof AppPremiacaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premiacao/metas': {
      id: '/app/premiacao/metas'
      path: '/premiacao/metas'
      fullPath: '/app/premiacao/metas'
      preLoaderRoute: typeof AppPremiacaoMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seguranca/video': {
      id: '/app/seguranca/video'
      path: '/seguranca/video'
      fullPath: '/app/seguranca/video'
      preLoaderRoute: typeof AppSegurancaVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/': {
      id: '/app/veiculos/'
      path: '/veiculos'
      fullPath: '/app/veiculos/'
      preLoaderRoute: typeof AppVeiculosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/novo': {
      id: '/app/veiculos/novo'
      path: '/veiculos/novo'
      fullPath: '/app/veiculos/novo'
      preLoaderRoute: typeof AppVeiculosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/viagens/': {
      id: '/app/fretamento/viagens/'
      path: '/fretamento/viagens'
      fullPath: '/app/fretamento/viagens/'
      preLoaderRoute: typeof AppFretamentoViagensIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fretamento/viagens/nova': {
      id: '/app/fretamento/viagens/nova'
      path: '/fretamento/viagens/nova'
      fullPath: '/app/fretamento/viagens/nova'
      preLoaderRoute: typeof AppFretamentoViagensNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/motoristas/perfil/$nome': {
      id: '/app/motoristas/perfil/$nome'
      path: '/motoristas/perfil/$nome'
      fullPath: '/app/motoristas/perfil/$nome'
      preLoaderRoute: typeof AppMotoristasPerfilNomeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCo2Route: typeof AppCo2Route
  AppEstrategicoRoute: typeof AppEstrategicoRoute
  AppEventosRoute: typeof AppEventosRoute
  AppMapaRoute: typeof AppMapaRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCadastrosAlarmeRoute: typeof AppCadastrosAlarmeRoute
  AppCadastrosCercaRoute: typeof AppCadastrosCercaRoute
  AppCadastrosCombustivelRoute: typeof AppCadastrosCombustivelRoute
  AppCadastrosDispositivosRoute: typeof AppCadastrosDispositivosRoute
  AppCadastrosGaragensRoute: typeof AppCadastrosGaragensRoute
  AppCadastrosGruposRoute: typeof AppCadastrosGruposRoute
  AppCadastrosLinhasRoute: typeof AppCadastrosLinhasRoute
  AppCadastrosPontosRoute: typeof AppCadastrosPontosRoute
  AppCadastrosUnidadesRoute: typeof AppCadastrosUnidadesRoute
  AppCadastrosUsuariosRoute: typeof AppCadastrosUsuariosRoute
  AppFretamentoAssentosRoute: typeof AppFretamentoAssentosRoute
  AppFretamentoContratosRoute: typeof AppFretamentoContratosRoute
  AppFretamentoEscalaRoute: typeof AppFretamentoEscalaRoute
  AppFretamentoPassageirosRoute: typeof AppFretamentoPassageirosRoute
  AppFretamentoPontoRoute: typeof AppFretamentoPontoRoute
  AppFretamentoRoteirizacaoRoute: typeof AppFretamentoRoteirizacaoRoute
  AppFrotaAnaliseRoute: typeof AppFrotaAnaliseRoute
  AppFrotaDesempenhoRoute: typeof AppFrotaDesempenhoRoute
  AppFrotaManutencaoRoute: typeof AppFrotaManutencaoRoute
  AppFrotaOrdensRoute: typeof AppFrotaOrdensRoute
  AppFrotaPneusRoute: typeof AppFrotaPneusRoute
  AppFrotaRegeneracaoRoute: typeof AppFrotaRegeneracaoRoute
  AppFrotaTelemetriaRoute: typeof AppFrotaTelemetriaRoute
  AppGerencialIndicadoresRoute: typeof AppGerencialIndicadoresRoute
  AppMotoristasNovoRoute: typeof AppMotoristasNovoRoute
  AppOperacaoAlarmesRoute: typeof AppOperacaoAlarmesRoute
  AppOperacaoViagensRoute: typeof AppOperacaoViagensRoute
  AppPessoasJornadaRoute: typeof AppPessoasJornadaRoute
  AppPremiacaoMetasRoute: typeof AppPremiacaoMetasRoute
  AppSegurancaVideoRoute: typeof AppSegurancaVideoRoute
  AppVeiculosNovoRoute: typeof AppVeiculosNovoRoute
  AppMotoristasIndexRoute: typeof AppMotoristasIndexRoute
  AppPremiacaoIndexRoute: typeof AppPremiacaoIndexRoute
  AppVeiculosIndexRoute: typeof AppVeiculosIndexRoute
  AppFretamentoViagensNovaRoute: typeof AppFretamentoViagensNovaRoute
  AppMotoristasPerfilNomeRoute: typeof AppMotoristasPerfilNomeRoute
  AppFretamentoViagensIndexRoute: typeof AppFretamentoViagensIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCo2Route: AppCo2Route,
  AppEstrategicoRoute: AppEstrategicoRoute,
  AppEventosRoute: AppEventosRoute,
  AppMapaRoute: AppMapaRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
  AppCadastrosAlarmeRoute: AppCadastrosAlarmeRoute,
  AppCadastrosCercaRoute: AppCadastrosCercaRoute,
  AppCadastrosCombustivelRoute: AppCadastrosCombustivelRoute,
  AppCadastrosDispositivosRoute: AppCadastrosDispositivosRoute,
  AppCadastrosGaragensRoute: AppCadastrosGaragensRoute,
  AppCadastrosGruposRoute: AppCadastrosGruposRoute,
  AppCadastrosLinhasRoute: AppCadastrosLinhasRoute,
  AppCadastrosPontosRoute: AppCadastrosPontosRoute,
  AppCadastrosUnidadesRoute: AppCadastrosUnidadesRoute,
  AppCadastrosUsuariosRoute: AppCadastrosUsuariosRoute,
  AppFretamentoAssentosRoute: AppFretamentoAssentosRoute,
  AppFretamentoContratosRoute: AppFretamentoContratosRoute,
  AppFretamentoEscalaRoute: AppFretamentoEscalaRoute,
  AppFretamentoPassageirosRoute: AppFretamentoPassageirosRoute,
  AppFretamentoPontoRoute: AppFretamentoPontoRoute,
  AppFretamentoRoteirizacaoRoute: AppFretamentoRoteirizacaoRoute,
  AppFrotaAnaliseRoute: AppFrotaAnaliseRoute,
  AppFrotaDesempenhoRoute: AppFrotaDesempenhoRoute,
  AppFrotaManutencaoRoute: AppFrotaManutencaoRoute,
  AppFrotaOrdensRoute: AppFrotaOrdensRoute,
  AppFrotaPneusRoute: AppFrotaPneusRoute,
  AppFrotaRegeneracaoRoute: AppFrotaRegeneracaoRoute,
  AppFrotaTelemetriaRoute: AppFrotaTelemetriaRoute,
  AppGerencialIndicadoresRoute: AppGerencialIndicadoresRoute,
  AppMotoristasNovoRoute: AppMotoristasNovoRoute,
  AppOperacaoAlarmesRoute: AppOperacaoAlarmesRoute,
  AppOperacaoViagensRoute: AppOperacaoViagensRoute,
  AppPessoasJornadaRoute: AppPessoasJornadaRoute,
  AppPremiacaoMetasRoute: AppPremiacaoMetasRoute,
  AppSegurancaVideoRoute: AppSegurancaVideoRoute,
  AppVeiculosNovoRoute: AppVeiculosNovoRoute,
  AppMotoristasIndexRoute: AppMotoristasIndexRoute,
  AppPremiacaoIndexRoute: AppPremiacaoIndexRoute,
  AppVeiculosIndexRoute: AppVeiculosIndexRoute,
  AppFretamentoViagensNovaRoute: AppFretamentoViagensNovaRoute,
  AppMotoristasPerfilNomeRoute: AppMotoristasPerfilNomeRoute,
  AppFretamentoViagensIndexRoute: AppFretamentoViagensIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
